pub mod alert_queue;
pub mod alerts;
pub mod canisters;
pub mod delivery;
pub mod detector;
pub mod fetcher;
pub mod icrc;
#[cfg(test)]
mod integration_tests;

use candid::{CandidType, Deserialize, Principal};
use ic_cdk::{api, caller, init, query, update};
use ic_stable_structures::memory_manager::{MemoryId, MemoryManager, VirtualMemory};
use ic_stable_structures::storable::Bound;
use ic_stable_structures::{DefaultMemoryImpl, StableBTreeMap, Storable};
use serde::Serialize;
use std::borrow::Cow;
use std::cell::RefCell;
use std::collections::BTreeMap;

use alerts::format_alert;
use canisters::{MAX_EVENTS_PER_USER, MAX_SEEN_TX_IDS_PER_USER};
#[allow(unused_imports)]
use delivery::AlertChannel;
use detector::{evaluate, DetectionContext};
use fetcher::{merge_into_ring_buffer, update_watermark_after_fetch};
use icrc::IcrcAccount;

// ---------------------------------------------------------------------------
// Security constants
// ---------------------------------------------------------------------------
const MIN_CYCLE_BALANCE: u64 = 500_000_000_000; // 500B cycles – cycle drain guard
const MAX_INGRESS_PAYLOAD_BYTES: u64 = 1_000_000; // 1 MB
#[cfg(test)]
pub const MIN_CYCLE_BALANCE_PUB: u64 = MIN_CYCLE_BALANCE;

// ---------------------------------------------------------------------------
// C1 Fix: MemoryManager with separate VirtualMemory regions per StableBTreeMap
// ---------------------------------------------------------------------------

/// Type alias for virtual memory backed by DefaultMemoryImpl.
pub(crate) type Memory = VirtualMemory<DefaultMemoryImpl>;

/// Memory region IDs — each StableBTreeMap must have a unique MemoryId.
const WATERMARKS_MEM_ID: MemoryId = MemoryId::new(0);
const ALERTS_MEM_ID: MemoryId = MemoryId::new(1);
const META_MEM_ID: MemoryId = MemoryId::new(2);
const USER_EVENTS_MEM_ID: MemoryId = MemoryId::new(3);
const SEEN_TX_IDS_MEM_ID: MemoryId = MemoryId::new(4); // H3: tx deduplication
// Note: MemoryId 5 is used by alert_queue.rs (ALERT_QUEUE_MEM_ID).
const USER_ALERT_CHANNELS_MEM_ID: MemoryId = MemoryId::new(6); // Phase 2c: per-user channel cache

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

#[derive(CandidType, Deserialize, Serialize, Clone, Debug, PartialEq)]
pub enum Chain {
    ICP,
    CkBTC,
    CkETH,
}

impl Chain {
    /// Return a stable u8 discriminant for use as a BTreeMap key byte.
    pub fn discriminant(&self) -> u8 {
        match self {
            Chain::ICP => 0,
            Chain::CkBTC => 1,
            Chain::CkETH => 2,
        }
    }

    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Chain::ICP),
            1 => Some(Chain::CkBTC),
            2 => Some(Chain::CkETH),
            _ => None,
        }
    }
}

#[derive(CandidType, Deserialize, Serialize, Clone, Debug, PartialEq)]
pub enum Direction {
    In,
    Out,
}

#[derive(CandidType, Deserialize, Serialize, Clone, Debug, PartialEq)]
pub enum AlertStatus {
    Pending,
    Sent,
    Failed,
}

// ---------------------------------------------------------------------------
// Core data structures
// ---------------------------------------------------------------------------

/// Normalised transaction event across all monitored chains.
/// `amount_e8s` is u128 to support ckETH (18 decimals, max ~10^21 Wei > u64::MAX).
#[derive(CandidType, Deserialize, Serialize, Clone, Debug)]
pub struct UnifiedEvent {
    pub chain: String,
    pub timestamp: u64,
    pub direction: Direction,
    pub amount_e8s: u128,
    pub counterparty: Principal,
    pub tx_id: String,
}

/// Record of an alert that was generated by the engine.
#[derive(CandidType, Deserialize, Serialize, Clone, Debug)]
pub struct AlertRecord {
    pub alert_id: String,
    pub timestamp: u64,
    pub user: Principal,
    pub rules_triggered: Vec<String>,
    pub severity: u8,
    pub status: AlertStatus,
}

impl Storable for AlertRecord {
    fn to_bytes(&self) -> Cow<'_, [u8]> {
        Cow::Owned(candid::encode_one(self).unwrap())
    }
    // C5 Fix: use expect() instead of unwrap()
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        candid::decode_one(&bytes)
            .expect("AlertRecord::from_bytes: failed to decode — stable memory may be corrupt")
    }
    const BOUND: Bound = Bound::Unbounded;
}

/// Per-chain polling watermark stored in stable memory.
#[derive(CandidType, Deserialize, Serialize, Clone, Debug, Default)]
pub struct Watermark {
    pub last_tx_id: String,
    pub last_checked: u64,
    pub block_height: u64,
}

impl Storable for Watermark {
    fn to_bytes(&self) -> Cow<'_, [u8]> {
        Cow::Owned(candid::encode_one(self).unwrap())
    }
    // C5 Fix: use unwrap_or_default() — Watermark has a safe Default
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        candid::decode_one(&bytes)
            .unwrap_or_default()
    }
    const BOUND: Bound = Bound::Unbounded;
}

/// Stable-memory key for the watermark map: (principal bytes + chain discriminant).
/// We encode as a 30-byte fixed array: 29 bytes principal + 1 byte chain.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct WatermarkKey(pub [u8; 30]);

impl WatermarkKey {
    pub fn new(principal: &Principal, chain: &Chain) -> Self {
        let pb = principal.as_slice();
        let mut key = [0u8; 30];
        let len = pb.len().min(29);
        key[..len].copy_from_slice(&pb[..len]);
        key[29] = chain.discriminant();
        WatermarkKey(key)
    }
}

impl Storable for WatermarkKey {
    fn to_bytes(&self) -> Cow<'_, [u8]> {
        Cow::Owned(self.0.to_vec())
    }
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        let mut arr = [0u8; 30];
        let len = bytes.len().min(30);
        arr[..len].copy_from_slice(&bytes[..len]);
        WatermarkKey(arr)
    }
    const BOUND: Bound = Bound::Bounded { max_size: 30, is_fixed_size: true };
}

/// Tiny wrapper for last_tick stored in stable memory.
#[derive(CandidType, Deserialize, Serialize, Clone, Debug, Default)]
struct LastTick {
    pub value: u64,
}

impl Storable for LastTick {
    fn to_bytes(&self) -> Cow<'_, [u8]> {
        Cow::Owned(candid::encode_one(self).unwrap())
    }
    // C5 Fix: use unwrap_or_default() — LastTick has a safe Default
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        candid::decode_one(&bytes).unwrap_or_default()
    }
    const BOUND: Bound = Bound::Unbounded;
}

/// Wrapper for config canister principal stored in stable memory.
#[derive(CandidType, Deserialize, Serialize, Clone, Debug, Default)]
struct StoredPrincipal {
    pub value: Option<Principal>,
}

impl Storable for StoredPrincipal {
    fn to_bytes(&self) -> Cow<'_, [u8]> {
        Cow::Owned(candid::encode_one(self).unwrap())
    }
    // C5 Fix: use unwrap_or_default() — StoredPrincipal has a safe Default
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        candid::decode_one(&bytes).unwrap_or_default()
    }
    const BOUND: Bound = Bound::Unbounded;
}

/// Phase 2c: Cached alert channel entry for a user.
///
/// Stores the parsed `AlertChannel` list fetched from the config canister,
/// along with the nanosecond timestamp when the cache was last populated.
/// Entries are invalidated after `CHANNEL_CACHE_TTL_NS` (5 minutes).
#[derive(CandidType, Deserialize, Serialize, Clone, Debug, Default)]
pub struct UserChannelEntry {
    pub channels: Vec<delivery::AlertChannel>,
    pub cached_at: u64,
}

impl Storable for UserChannelEntry {
    fn to_bytes(&self) -> Cow<'_, [u8]> {
        Cow::Owned(candid::encode_one(self).unwrap())
    }
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        candid::decode_one(&bytes).unwrap_or_default()
    }
    const BOUND: Bound = Bound::Unbounded;
}

/// Cache TTL for user alert channels: 5 minutes in nanoseconds.
pub const CHANNEL_CACHE_TTL_NS: u64 = 300 * 1_000_000_000;

// ---------------------------------------------------------------------------
// Health response type
// ---------------------------------------------------------------------------

#[derive(CandidType, Deserialize, Serialize, Clone, Debug)]
pub struct EngineHealthStatus {
    pub cycle_balance: u64,
    pub last_tick: u64,
    pub is_running: bool,
    pub watermark_count: u64,
}

// ---------------------------------------------------------------------------
// Stable storage (thread-local)
// ---------------------------------------------------------------------------

/// Stable key used for the single-slot "last_tick" record.
const LAST_TICK_KEY: &str = "__last_tick__";
/// Stable key for config canister principal.
const CONFIG_CANISTER_KEY: &str = "__config_canister__";

thread_local! {
    // C1 Fix: Single MemoryManager that owns all virtual memory regions.
    static MEMORY_MANAGER: RefCell<MemoryManager<DefaultMemoryImpl>> =
        RefCell::new(MemoryManager::init(DefaultMemoryImpl::default()));

    /// Watermarks: (principal || chain_discriminant) → Watermark
    static WATERMARKS: RefCell<StableBTreeMap<WatermarkKey, Watermark, Memory>> =
        RefCell::new(StableBTreeMap::new(
            MEMORY_MANAGER.with(|mm| mm.borrow().get(WATERMARKS_MEM_ID))
        ));

    /// Alert history: alert_id → AlertRecord
    static ALERTS: RefCell<StableBTreeMap<String, AlertRecord, Memory>> =
        RefCell::new(StableBTreeMap::new(
            MEMORY_MANAGER.with(|mm| mm.borrow().get(ALERTS_MEM_ID))
        ));

    /// Single-slot metadata (last_tick, config canister id, …)
    static META: RefCell<StableBTreeMap<String, Vec<u8>, Memory>> =
        RefCell::new(StableBTreeMap::new(
            MEMORY_MANAGER.with(|mm| mm.borrow().get(META_MEM_ID))
        ));

    /// Per-user event ring buffer: WatermarkKey → candid-encoded Vec<UnifiedEvent>
    /// We reuse WatermarkKey as a 30-byte principal key (chain byte = 0xFF for event store).
    static USER_EVENTS: RefCell<StableBTreeMap<WatermarkKey, Vec<u8>, Memory>> =
        RefCell::new(StableBTreeMap::new(
            MEMORY_MANAGER.with(|mm| mm.borrow().get(USER_EVENTS_MEM_ID))
        ));

    /// H3 Fix: Per-user seen tx IDs for deduplication.
    /// WatermarkKey (chain byte = 0xFE) → candid-encoded BTreeMap<String, u64>
    static SEEN_TX_IDS: RefCell<StableBTreeMap<WatermarkKey, Vec<u8>, Memory>> =
        RefCell::new(StableBTreeMap::new(
            MEMORY_MANAGER.with(|mm| mm.borrow().get(SEEN_TX_IDS_MEM_ID))
        ));

    /// Phase 2c: Per-user alert channel cache.
    /// Principal text → UserChannelEntry (parsed AlertChannels + cache timestamp)
    static USER_ALERT_CHANNELS: RefCell<StableBTreeMap<String, UserChannelEntry, Memory>> =
        RefCell::new(StableBTreeMap::new(
            MEMORY_MANAGER.with(|mm| mm.borrow().get(USER_ALERT_CHANNELS_MEM_ID))
        ));

    /// Runtime flag: has the timer been started?
    static IS_RUNNING: RefCell<bool> = const { RefCell::new(false) };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn get_last_tick() -> u64 {
    META.with(|m| {
        m.borrow()
            .get(&LAST_TICK_KEY.to_string())
            .and_then(|b| candid::decode_one::<LastTick>(&b).ok())
            .map(|lt| lt.value)
            .unwrap_or(0)
    })
}

fn set_last_tick(ts: u64) {
    META.with(|m| {
        let bytes = candid::encode_one(&LastTick { value: ts }).unwrap();
        m.borrow_mut().insert(LAST_TICK_KEY.to_string(), bytes);
    });
}

fn get_config_canister_id() -> Option<Principal> {
    META.with(|m| {
        m.borrow()
            .get(&CONFIG_CANISTER_KEY.to_string())
            .and_then(|b| candid::decode_one::<StoredPrincipal>(&b).ok())
            .and_then(|sp| sp.value)
    })
}

fn store_config_canister_id(id: Principal) {
    META.with(|m| {
        let bytes = candid::encode_one(&StoredPrincipal { value: Some(id) }).unwrap();
        m.borrow_mut().insert(CONFIG_CANISTER_KEY.to_string(), bytes);
    });
}

// ---------------------------------------------------------------------------
// Phase 2c: Per-user alert channel cache helpers
// ---------------------------------------------------------------------------

/// Read cached channels for `user` if the entry exists and is still fresh.
/// Returns `None` if not cached or if the cache has expired (> 5 minutes old).
pub fn get_cached_channels(user: &Principal, now_ns: u64) -> Option<Vec<delivery::AlertChannel>> {
    let key = user.to_text();
    USER_ALERT_CHANNELS.with(|uc| {
        uc.borrow().get(&key).and_then(|entry| {
            if now_ns.saturating_sub(entry.cached_at) < CHANNEL_CACHE_TTL_NS {
                Some(entry.channels.clone())
            } else {
                None // expired
            }
        })
    })
}

/// Store a channel list in the cache for `user` with the current timestamp.
pub fn store_cached_channels(user: &Principal, channels: Vec<delivery::AlertChannel>, now_ns: u64) {
    let key = user.to_text();
    USER_ALERT_CHANNELS.with(|uc| {
        uc.borrow_mut().insert(key, UserChannelEntry { channels, cached_at: now_ns });
    });
}

/// Return the number of entries currently in the channel cache.
pub fn channel_cache_len() -> u64 {
    USER_ALERT_CHANNELS.with(|uc| uc.borrow().len())
}

/// Fetch alert channels for a user:
///   1. Check the in-memory cache (valid for 5 min).
///   2. If stale / missing, call the config canister (with up to 3 retries).
///   3. On inter-canister error, return empty vec (fail open — skip delivery
///      rather than hard-failing the alert).
///
/// In test builds this always returns an empty vec (no IC runtime available).
#[cfg(not(test))]
pub async fn fetch_user_alert_channels(user: Principal) -> Vec<delivery::AlertChannel> {
    let now_ns = ic_cdk::api::time();

    // 1. Cache hit
    if let Some(channels) = get_cached_channels(&user, now_ns) {
        return channels;
    }

    // 2. Inter-canister call with retry
    let config_id = match get_config_canister_id() {
        Some(id) => id,
        None => {
            ic_cdk::println!(
                "[channels] config canister not set; cannot fetch channels for {}",
                user
            );
            return vec![];
        }
    };

    let mut last_err = String::new();
    for attempt in 0..3u32 {
        use canisters::{ApiResult as CfgResult, GuardianConfigChannels};
        match ic_cdk::call::<(Principal,), (CfgResult<GuardianConfigChannels>,)>(
            config_id,
            "get_config_for_user",
            (user,),
        )
        .await
        {
            Ok((CfgResult::Ok(cfg),)) => {
                let channels: Vec<delivery::AlertChannel> = cfg
                    .alert_channels
                    .iter()
                    .filter_map(|s| delivery::AlertChannel::from_str_config(s))
                    .collect();
                store_cached_channels(&user, channels.clone(), now_ns);
                ic_cdk::println!(
                    "[channels] fetched {} channels for {} (attempt {})",
                    channels.len(), user, attempt + 1
                );
                return channels;
            }
            Ok((CfgResult::Err(e),)) => {
                // Config not found — cache empty vec so we don't hammer on every drain
                ic_cdk::println!("[channels] config not found for {}: {}", user, e);
                store_cached_channels(&user, vec![], now_ns);
                return vec![];
            }
            Err((code, msg)) => {
                last_err = format!("{:?}: {}", code, msg);
                ic_cdk::println!(
                    "[channels] inter-canister error for {} (attempt {}): {}",
                    user, attempt + 1, last_err
                );
                // Brief pause before retry — we yield to the async runtime briefly
                // (true 100ms sleep not available in IC canisters, but yielding
                //  to the event loop provides some backoff)
                if attempt < 2 {
                    // Yield point: call a dummy self-call to introduce latency
                    // In practice the IC scheduler provides natural backoff between
                    // inter-canister call rounds (~100ms per round trip).
                    let _: Result<(), _> = ic_cdk::call(ic_cdk::id(), "get_health", ()).await;
                }
            }
        }
    }

    // All retries exhausted — return empty to avoid blocking delivery
    ic_cdk::println!(
        "[channels] all retries failed for {}; last error: {}",
        user, last_err
    );
    vec![]
}

#[cfg(test)]
pub async fn fetch_user_alert_channels(_user: Principal) -> Vec<delivery::AlertChannel> {
    vec![] // No IC runtime in tests
}

// ---------------------------------------------------------------------------
// Phase 2c: Per-user delivery drain (called from delivery_tick)
// ---------------------------------------------------------------------------

/// Drain up to `max_items` from the alert queue, routing each alert to the
/// user's configured channels fetched from the config canister cache.
///
/// Returns `(delivered, retried, failed_perm)`.
#[cfg(not(test))]
async fn run_per_user_delivery_drain(max_items: usize) -> (u32, u32, u32) {
    use crate::alert_queue::{dequeue_alerts, enqueue_alert};

    let items = dequeue_alerts(max_items);
    let mut delivered = 0u32;
    let mut retried = 0u32;
    let mut failed_perm = 0u32;

    for mut item in items {
        // Fetch channels for this specific user
        let channels = fetch_user_alert_channels(item.user).await;

        if channels.is_empty() {
            ic_cdk::println!(
                "[delivery] no channels configured for user {} — skipping alert {}",
                item.user, item.alert_id
            );
            // Re-enqueue for later (config may be set up eventually)
            // Count as retry unless we've exhausted attempts
            if item.retry_count + 1 >= delivery::MAX_RETRIES {
                failed_perm += 1;
                ALERTS.with(|a| {
                    if let Some(mut rec) = a.borrow().get(&item.alert_id) {
                        rec.status = AlertStatus::Failed;
                        a.borrow_mut().insert(item.alert_id.clone(), rec);
                    }
                });
            } else {
                item.retry_count += 1;
                enqueue_alert(item);
                retried += 1;
            }
            continue;
        }

        let mut any_success = false;
        let mut perm_fail = false;
        let mut all_channel_results: Vec<bool> = Vec::new();

        for channel in &channels {
            let outcome = delivery::deliver_to_channel(
                channel,
                &item.alert_id,
                &item.severity,
                item.severity_score,
                &item.rules_triggered,
                &item.events_summary,
                &item.recommended_action,
            )
            .await;

            if outcome.is_success() {
                all_channel_results.push(true);
                any_success = true;
                ic_cdk::println!(
                    "[delivery] ✓ alert {} → {} (user {})",
                    item.alert_id, channel.kind_label(), item.user
                );
            } else if outcome.is_permanent_failure() {
                all_channel_results.push(false);
                perm_fail = true;
                ic_cdk::println!(
                    "[delivery] ✗ permanent failure alert {} → {}: {:?}",
                    item.alert_id, channel.kind_label(), outcome
                );
            } else {
                all_channel_results.push(false);
                ic_cdk::println!(
                    "[delivery] ~ transient failure alert {} → {}: {:?}",
                    item.alert_id, channel.kind_label(), outcome
                );
            }
        }

        // Mark Sent only if at least one channel succeeded
        if any_success {
            delivered += 1;
            ALERTS.with(|a| {
                if let Some(mut rec) = a.borrow().get(&item.alert_id) {
                    rec.status = AlertStatus::Sent;
                    a.borrow_mut().insert(item.alert_id.clone(), rec);
                }
            });
        } else if perm_fail || item.retry_count + 1 >= delivery::MAX_RETRIES {
            failed_perm += 1;
            ALERTS.with(|a| {
                if let Some(mut rec) = a.borrow().get(&item.alert_id) {
                    rec.status = AlertStatus::Failed;
                    a.borrow_mut().insert(item.alert_id.clone(), rec);
                }
            });
            ic_cdk::println!(
                "[delivery] ✗ alert {} permanently failed after {} attempts",
                item.alert_id, item.retry_count + 1
            );
        } else {
            item.retry_count += 1;
            enqueue_alert(item);
            retried += 1;
        }
    }

    (delivered, retried, failed_perm)
}

// ---------------------------------------------------------------------------
// Phase 2c: Config sync tick — pre-populates channel cache for all active users
// ---------------------------------------------------------------------------

/// Called every 300 seconds — pre-fetches and caches alert channel configs for
/// all active users (those with watermarks or queued alerts) so that the 60s
/// delivery tick has fresh data without needing to do inter-canister calls.
#[cfg(not(test))]
fn config_sync_tick() {
    ic_cdk::spawn(async move {
        config_sync_async().await;
    });
}

#[cfg(not(test))]
async fn config_sync_async() {
    let now_ns = ic_cdk::api::time();

    // Collect all unique principals from watermarks (active monitored users)
    let principals: Vec<Principal> = WATERMARKS.with(|w| {
        w.borrow()
            .iter()
            .map(|(key, _)| {
                let slice = &key.0[..29];
                let end = slice.iter().rposition(|&b| b != 0).map(|i| i + 1).unwrap_or(0);
                Principal::from_slice(&slice[..end])
            })
            .collect::<std::collections::HashSet<Principal>>()
            .into_iter()
            .collect()
    });

    let user_count = principals.len();
    let mut total_channels = 0usize;

    for principal in principals {
        let channels = fetch_user_alert_channels(principal).await;
        total_channels += channels.len();
        store_cached_channels(&principal, channels, now_ns);
    }

    ic_cdk::println!(
        "[config_sync] Synced channels for {} users, {} total channels",
        user_count, total_channels
    );
}

/// Cycle drain protection — panics (traps) if balance is critically low.
fn guard_cycles() {
    let balance = api::canister_balance();
    if balance < MIN_CYCLE_BALANCE {
        ic_cdk::trap(&format!(
            "Cycle drain guard: balance {} < minimum {}",
            balance, MIN_CYCLE_BALANCE
        ));
    }
}

/// Reject anonymous callers on update endpoints.
fn reject_anonymous() {
    if caller() == Principal::anonymous() {
        ic_cdk::trap("Anonymous callers are not permitted");
    }
}

/// C3 Fix: Reject non-controller callers for privileged admin endpoints.
fn reject_non_controller() {
    let c = caller();
    if !ic_cdk::api::is_controller(&c) {
        ic_cdk::trap("Only controllers can call this method");
    }
}

// ---------------------------------------------------------------------------
// Timer
// ---------------------------------------------------------------------------

/// Called every 30 seconds by the IC timer.
fn timer_tick() {
    let ts = api::time();
    ic_cdk::println!("Guardian tick at {}", ts);

    // Cycle balance check (log only inside the timer — don't trap here)
    let balance = api::canister_balance();
    if balance < MIN_CYCLE_BALANCE {
        ic_cdk::println!(
            "WARNING: cycle balance {} below minimum {}",
            balance,
            MIN_CYCLE_BALANCE
        );
    }

    // Update health status
    set_last_tick(ts);

    // Phase 1c: spawn async fetch for all users (not in test builds — no ic_cdk runtime)
    #[cfg(not(test))]
    ic_cdk::spawn(async move {
        run_fetch_cycle(ts).await;
    });
}

/// Async fetch cycle: for each known watermark entry, fetch transactions from
/// all 3 chains, store new events in the ring buffer, and update watermarks.
#[cfg(not(test))]
async fn run_fetch_cycle(now_ns: u64) {
    // Collect all unique principals from the watermark map.
    let principals: Vec<Principal> = WATERMARKS.with(|w| {
        w.borrow()
            .iter()
            .map(|(key, _)| {
                // First 29 bytes of key encode the principal slice.
                let slice = &key.0[..29];
                // Strip trailing zero padding to reconstruct.
                let end = slice.iter().rposition(|&b| b != 0).map(|i| i + 1).unwrap_or(0);
                Principal::from_slice(&slice[..end])
            })
            .collect::<std::collections::HashSet<Principal>>()
            .into_iter()
            .collect()
    });

    for principal in principals {
        let account = IcrcAccount::new(principal);

        // Fetch ICP
        let icp_wm_key = WatermarkKey::new(&principal, &Chain::ICP);
        let icp_wm = WATERMARKS.with(|w| w.borrow().get(&icp_wm_key).unwrap_or_default());
        match fetcher::fetch_icp_transactions(account.clone(), &icp_wm).await {
            Ok(events) => {
                let mut updated_wm = icp_wm.clone();
                update_watermark_after_fetch(&mut updated_wm, &events, now_ns);
                WATERMARKS.with(|w| w.borrow_mut().insert(icp_wm_key, updated_wm));
                store_user_events(&principal, events, now_ns);
            }
            Err(e) => ic_cdk::println!("ICP fetch error for {:?}: {}", principal, e),
        }

        // Fetch ckBTC
        let ckbtc_wm_key = WatermarkKey::new(&principal, &Chain::CkBTC);
        let ckbtc_wm = WATERMARKS.with(|w| w.borrow().get(&ckbtc_wm_key).unwrap_or_default());
        match fetcher::fetch_ckbtc_transactions(account.clone(), &ckbtc_wm).await {
            Ok(events) => {
                let mut updated_wm = ckbtc_wm.clone();
                update_watermark_after_fetch(&mut updated_wm, &events, now_ns);
                WATERMARKS.with(|w| w.borrow_mut().insert(ckbtc_wm_key, updated_wm));
                store_user_events(&principal, events, now_ns);
            }
            Err(e) => ic_cdk::println!("ckBTC fetch error for {:?}: {}", principal, e),
        }

        // Fetch ckETH
        let cketh_wm_key = WatermarkKey::new(&principal, &Chain::CkETH);
        let cketh_wm = WATERMARKS.with(|w| w.borrow().get(&cketh_wm_key).unwrap_or_default());
        match fetcher::fetch_cketh_transactions(account.clone(), &cketh_wm).await {
            Ok(events) => {
                let mut updated_wm = cketh_wm.clone();
                update_watermark_after_fetch(&mut updated_wm, &events, now_ns);
                WATERMARKS.with(|w| w.borrow_mut().insert(cketh_wm_key, updated_wm));
                store_user_events(&principal, events, now_ns);
            }
            Err(e) => ic_cdk::println!("ckETH fetch error for {:?}: {}", principal, e),
        }

        // --- Balance query: replace tx-history estimation with icrc1_balance_of ---
        // Try ICP ledger first; on failure fall back to estimation from tx history.
        let icp_ledger = candid::Principal::from_text(canisters::ICP_LEDGER_CANISTER_ID)
            .expect("ICP_LEDGER_CANISTER_ID is a valid principal");
        // icrc1_balance_of returns `nat` which we decode as u128 for ckETH compatibility.
        // ckETH uses 18 decimals; 1000 ETH = 10^21 Wei which overflows u64.
        let balance_e8s: Option<u128> = match ic_cdk::call::<(IcrcAccount,), (candid::Nat,)>(
            icp_ledger,
            "icrc1_balance_of",
            (account.clone(),),
        )
        .await
        {
            Ok((nat,)) => nat.0.try_into().ok(),
            Err(e) => {
                ic_cdk::println!("icrc1_balance_of failed for {:?}: {:?}", principal, e);
                None // fall back to estimation below
            }
        };

        // --- Detection engine ---
        // Load all stored events for this user and run rule evaluation.
        let user_events = load_user_events(&principal);
        if !user_events.is_empty() {
            // Fallback balance estimate: sum(In) - sum(Out), used when balance_e8s is None.
            // Use u128 to prevent overflow for ckETH balances.
            let total_in: u128 = user_events.iter()
                .filter(|e| e.direction == Direction::In)
                .map(|e| e.amount_e8s)
                .fold(0u128, |a, x| a.saturating_add(x));
            let total_out: u128 = user_events.iter()
                .filter(|e| e.direction == Direction::Out)
                .map(|e| e.amount_e8s)
                .fold(0u128, |a, x| a.saturating_add(x));
            let estimated_balance = total_in.saturating_sub(total_out);

            // Default config values (Phase 2: fetch from config canister)
            let alert_threshold: u8 = 7;
            let allowlisted: Vec<String> = vec![];

            let ctx = DetectionContext {
                events: &user_events,
                estimated_balance_e8s: estimated_balance,
                balance_e8s, // actual balance from ledger, or None on failure
                allowlisted_addresses: &allowlisted,
                alert_threshold,
            };

            let result = evaluate(&ctx);

            if result.should_alert {
                let severity_str = result.severity.as_str().to_string();
                let payload = format_alert(principal, result, user_events.clone(), now_ns);
                ic_cdk::println!("ALERT: {} for {:?} (alert_id={})", severity_str, principal, payload.alert_id);

                // Enqueue for Phase 2b HTTPS outcall delivery
                alert_queue::enqueue_alert(alert_queue::AlertQueueItem {
                    alert_id: payload.alert_id.clone(),
                    user: principal,
                    severity: payload.severity.clone(),
                    severity_score: payload.severity_score,
                    rules_triggered: payload.rules_triggered.clone(),
                    events_summary: payload.events_summary.clone(),
                    recommended_action: payload.recommended_action.clone(),
                    retry_count: 0,
                    created_at: now_ns,
                });
            }
        }
    }
}

/// Load all events stored for a user from stable memory.
fn load_user_events(principal: &Principal) -> Vec<UnifiedEvent> {
    let key = user_events_key(principal);
    USER_EVENTS.with(|ue| {
        ue.borrow()
            .get(&key)
            .and_then(|b| candid::decode_one::<Vec<UnifiedEvent>>(&b).ok())
            .unwrap_or_default()
    })
}

/// H3 Fix: Build the per-user seen-tx-ids WatermarkKey (chain byte = 0xFE).
fn seen_tx_ids_key(principal: &Principal) -> WatermarkKey {
    let pb = principal.as_slice();
    let mut key = [0u8; 30];
    let len = pb.len().min(29);
    key[..len].copy_from_slice(&pb[..len]);
    key[29] = 0xFE; // sentinel: seen-tx-ids store
    WatermarkKey(key)
}

/// H3 Fix: Load the map of already-seen tx IDs → insertion timestamp (ns) for a user.
fn load_seen_tx_ids(principal: &Principal) -> BTreeMap<String, u64> {
    let key = seen_tx_ids_key(principal);
    SEEN_TX_IDS.with(|s| {
        s.borrow()
            .get(&key)
            .and_then(|b| candid::decode_one::<BTreeMap<String, u64>>(&b).ok())
            .unwrap_or_default()
    })
}

/// H3 Fix: Persist the seen tx ID map for a user (bounded to MAX_SEEN_TX_IDS_PER_USER).
fn save_seen_tx_ids(principal: &Principal, ids: &BTreeMap<String, u64>) {
    let key = seen_tx_ids_key(principal);
    let encoded = candid::encode_one(ids).unwrap_or_default();
    SEEN_TX_IDS.with(|s| s.borrow_mut().insert(key, encoded));
}

/// Merge `new_events` into the per-user ring buffer in stable memory.
/// H3 Fix: Deduplicates events by tx_id before merging.
/// TTL Fix: Prunes seen tx IDs older than 24 hours to prevent unbounded growth.
fn store_user_events(principal: &Principal, new_events: Vec<UnifiedEvent>, now_ns: u64) {
    if new_events.is_empty() {
        return;
    }

    const TTL_NS: u64 = 86_400 * 1_000_000_000; // 24 hours in nanoseconds

    // H3 Fix: Filter out already-seen tx IDs
    let mut seen = load_seen_tx_ids(principal);
    let deduplicated: Vec<UnifiedEvent> = new_events
        .into_iter()
        .filter(|e| !seen.contains_key(&e.tx_id))
        .collect();

    if deduplicated.is_empty() {
        return;
    }

    // Record the new tx IDs with their insertion timestamp
    for e in &deduplicated {
        seen.insert(e.tx_id.clone(), now_ns);
    }

    // TTL Fix: prune entries older than 24 hours
    seen.retain(|_, ts| now_ns.saturating_sub(*ts) < TTL_NS);

    // Fallback cap: if still above limit after TTL prune, remove oldest by timestamp
    if seen.len() > MAX_SEEN_TX_IDS_PER_USER {
        let mut by_age: Vec<(String, u64)> = seen.iter().map(|(k, &v)| (k.clone(), v)).collect();
        by_age.sort_by_key(|(_, ts)| *ts);
        let to_remove = by_age.len() - MAX_SEEN_TX_IDS_PER_USER;
        for (k, _) in by_age.into_iter().take(to_remove) {
            seen.remove(&k);
        }
    }

    save_seen_tx_ids(principal, &seen);

    let key = user_events_key(principal);
    let mut existing: Vec<UnifiedEvent> = USER_EVENTS.with(|ue| {
        ue.borrow()
            .get(&key)
            .and_then(|b| candid::decode_one::<Vec<UnifiedEvent>>(&b).ok())
            .unwrap_or_default()
    });
    merge_into_ring_buffer(&mut existing, deduplicated, MAX_EVENTS_PER_USER);
    let encoded = candid::encode_one(&existing).unwrap_or_default();
    USER_EVENTS.with(|ue| ue.borrow_mut().insert(key, encoded));
}

/// Build a WatermarkKey used as the user-events ring-buffer key.
/// We use chain discriminant 0xFF to distinguish from watermark keys.
fn user_events_key(principal: &Principal) -> WatermarkKey {
    let pb = principal.as_slice();
    let mut key = [0u8; 30];
    let len = pb.len().min(29);
    key[..len].copy_from_slice(&pb[..len]);
    key[29] = 0xFF; // sentinel: not a real chain discriminant
    WatermarkKey(key)
}

// ---------------------------------------------------------------------------
// C4 Fix: inspect_message for engine canister — reject anonymous and oversized
// ---------------------------------------------------------------------------

#[ic_cdk::inspect_message]
fn inspect_message() {
    // Reject anonymous callers at the ingress gate
    if caller() == Principal::anonymous() {
        ic_cdk::trap("Anonymous callers are not permitted");
    }

    // Reject oversized payloads to prevent cycle drain attacks
    let arg_size = ic_cdk::api::call::arg_data_raw().len() as u64;
    if arg_size > MAX_INGRESS_PAYLOAD_BYTES {
        ic_cdk::trap(&format!(
            "Payload too large: {} bytes exceeds maximum of {} bytes",
            arg_size, MAX_INGRESS_PAYLOAD_BYTES
        ));
    }

    // Accept the message — full authorization checked in update functions
    ic_cdk::api::call::accept_message();
}

// ---------------------------------------------------------------------------
// Canister lifecycle
// ---------------------------------------------------------------------------

#[init]
fn init() {
    // Start the 30-second heartbeat timer
    start_timer();
    ic_cdk::println!("Guardian Engine initialised");
}

/// C2 Fix: post_upgrade restarts the timer (which dies after every upgrade).
#[ic_cdk::post_upgrade]
fn post_upgrade() {
    start_timer();
    ic_cdk::println!("Guardian Engine post-upgrade: timer restarted");
}

/// Shared timer-start logic used by both init and post_upgrade.
fn start_timer() {
    // 30s monitoring tick
    ic_cdk_timers::set_timer_interval(
        std::time::Duration::from_secs(30),
        timer_tick,
    );
    // 60s delivery drain tick (Phase 2b/2c)
    ic_cdk_timers::set_timer_interval(
        std::time::Duration::from_secs(60),
        delivery_tick,
    );
    // 300s config sync tick (Phase 2c) — pre-fetches per-user channel configs
    #[cfg(not(test))]
    ic_cdk_timers::set_timer_interval(
        std::time::Duration::from_secs(300),
        config_sync_tick,
    );
    IS_RUNNING.with(|r| *r.borrow_mut() = true);
}

/// Called every 60 seconds — drains queued alerts via HTTPS outcalls.
/// Phase 2c: uses per-user channel routing via `run_per_user_delivery_drain`.
fn delivery_tick() {
    #[cfg(not(test))]
    ic_cdk::spawn(async move {
        let (delivered, retried, failed) = run_per_user_delivery_drain(10).await;
        ic_cdk::println!(
            "[delivery_tick] delivered={} retried={} failed_perm={}",
            delivered, retried, failed
        );
    });
}

// ---------------------------------------------------------------------------
// Query endpoints
// ---------------------------------------------------------------------------

#[query]
fn get_health() -> EngineHealthStatus {
    let cycle_balance = api::canister_balance();
    let last_tick = get_last_tick();
    let is_running = IS_RUNNING.with(|r| *r.borrow());
    let watermark_count = WATERMARKS.with(|w| w.borrow().len());

    EngineHealthStatus {
        cycle_balance,
        last_tick,
        is_running,
        watermark_count,
    }
}

// ---------------------------------------------------------------------------
// Query endpoints (Phase 2b additions)
// ---------------------------------------------------------------------------

/// Return the current number of alerts in the delivery queue.
#[query]
fn get_alert_queue_len() -> u64 {
    alert_queue::queue_len()
}

// ---------------------------------------------------------------------------
// Update endpoints
// ---------------------------------------------------------------------------

/// Store the principal of the companion guardian_config canister.
/// C3 Fix: Only controllers can call this — prevents any caller from redirecting
/// the engine to a malicious config canister.
#[update]
fn set_config_canister_id(id: Principal) {
    reject_anonymous();
    reject_non_controller(); // C3 Fix: controller-only
    guard_cycles();
    store_config_canister_id(id);
    ic_cdk::println!("Config canister id set to {:?}", id);
}

/// Stub: fetch user configurations from the config canister.
#[allow(dead_code)]
async fn fetch_user_configs() {
    ic_cdk::println!("fetching configs");
    if let Some(config_id) = get_config_canister_id() {
        ic_cdk::println!("Config canister: {:?}", config_id);
        // TODO Phase 1c: inter-canister call to guardian_config
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // --- Watermark -----------------------------------------------------------

    #[test]
    fn test_watermark_default() {
        let w = Watermark::default();
        assert_eq!(w.last_tx_id, "");
        assert_eq!(w.last_checked, 0);
        assert_eq!(w.block_height, 0);
    }

    #[test]
    fn test_watermark_storable_roundtrip() {
        let w = Watermark {
            last_tx_id: "tx-abc-123".to_string(),
            last_checked: 1_709_000_000_000_000_000,
            block_height: 42_000,
        };
        let bytes = w.to_bytes();
        let w2 = Watermark::from_bytes(bytes);
        assert_eq!(w2.last_tx_id, "tx-abc-123");
        assert_eq!(w2.last_checked, 1_709_000_000_000_000_000);
        assert_eq!(w2.block_height, 42_000);
    }

    #[test]
    fn test_watermark_storable_empty_tx_id() {
        let w = Watermark {
            last_tx_id: String::new(),
            last_checked: 0,
            block_height: 0,
        };
        let w2 = Watermark::from_bytes(w.to_bytes());
        assert_eq!(w2.last_tx_id, "");
    }

    // --- WatermarkKey --------------------------------------------------------

    #[test]
    fn test_watermark_key_encoding() {
        let p = Principal::from_slice(&[1u8; 29]);
        let key = WatermarkKey::new(&p, &Chain::ICP);
        assert_eq!(key.0[29], 0); // ICP discriminant
    }

    #[test]
    fn test_watermark_key_chain_discriminants() {
        let p = Principal::from_slice(&[2u8; 29]);
        assert_eq!(WatermarkKey::new(&p, &Chain::ICP).0[29], 0);
        assert_eq!(WatermarkKey::new(&p, &Chain::CkBTC).0[29], 1);
        assert_eq!(WatermarkKey::new(&p, &Chain::CkETH).0[29], 2);
    }

    #[test]
    fn test_watermark_key_storable_roundtrip() {
        let p = Principal::from_slice(&[3u8; 29]);
        let key = WatermarkKey::new(&p, &Chain::CkBTC);
        let key2 = WatermarkKey::from_bytes(key.to_bytes());
        assert_eq!(key, key2);
    }

    #[test]
    fn test_watermark_key_ordering() {
        let p1 = Principal::from_slice(&[1u8; 29]);
        let p2 = Principal::from_slice(&[2u8; 29]);
        let k1 = WatermarkKey::new(&p1, &Chain::ICP);
        let k2 = WatermarkKey::new(&p2, &Chain::ICP);
        assert!(k1 < k2);
    }

    // --- Chain ---------------------------------------------------------------

    #[test]
    fn test_chain_discriminant_roundtrip() {
        for chain in [Chain::ICP, Chain::CkBTC, Chain::CkETH] {
            let d = chain.discriminant();
            let back = Chain::from_discriminant(d).unwrap();
            assert_eq!(chain, back);
        }
    }

    #[test]
    fn test_chain_unknown_discriminant() {
        assert!(Chain::from_discriminant(99).is_none());
    }

    // --- AlertRecord ---------------------------------------------------------

    #[test]
    fn test_alert_record_creation() {
        let rec = AlertRecord {
            alert_id: "alert-001".to_string(),
            timestamp: 1_709_000_000_000_000_000,
            user: Principal::from_slice(&[4u8; 29]),
            rules_triggered: vec!["large_transfer".to_string()],
            severity: 7,
            status: AlertStatus::Pending,
        };
        assert_eq!(rec.alert_id, "alert-001");
        assert_eq!(rec.severity, 7);
        assert_eq!(rec.status, AlertStatus::Pending);
    }

    #[test]
    fn test_alert_record_status_transitions() {
        let mut rec = AlertRecord {
            alert_id: "alert-002".to_string(),
            timestamp: 0,
            user: Principal::from_slice(&[5u8; 29]),
            rules_triggered: vec![],
            severity: 3,
            status: AlertStatus::Pending,
        };
        assert_eq!(rec.status, AlertStatus::Pending);
        rec.status = AlertStatus::Sent;
        assert_eq!(rec.status, AlertStatus::Sent);
        rec.status = AlertStatus::Failed;
        assert_eq!(rec.status, AlertStatus::Failed);
    }

    #[test]
    fn test_alert_record_storable_roundtrip() {
        let rec = AlertRecord {
            alert_id: "alert-003".to_string(),
            timestamp: 999,
            user: Principal::from_slice(&[6u8; 29]),
            rules_triggered: vec!["rapid_tx".to_string(), "new_address".to_string()],
            severity: 10,
            status: AlertStatus::Sent,
        };
        let bytes = rec.to_bytes();
        let rec2 = AlertRecord::from_bytes(bytes);
        assert_eq!(rec2.alert_id, "alert-003");
        assert_eq!(rec2.rules_triggered.len(), 2);
        assert_eq!(rec2.status, AlertStatus::Sent);
    }

    // --- UnifiedEvent --------------------------------------------------------

    #[test]
    fn test_unified_event_fields() {
        let ev = UnifiedEvent {
            chain: "ICP".to_string(),
            timestamp: 100,
            direction: Direction::Out,
            amount_e8s: 1_000_000,
            counterparty: Principal::anonymous(),
            tx_id: "some-tx-id".to_string(),
        };
        assert_eq!(ev.chain, "ICP");
        assert_eq!(ev.direction, Direction::Out);
        assert_eq!(ev.amount_e8s, 1_000_000);
    }

    #[test]
    fn test_unified_event_direction_variants() {
        let e_in = UnifiedEvent {
            chain: "CkBTC".to_string(),
            timestamp: 0,
            direction: Direction::In,
            amount_e8s: 500,
            counterparty: Principal::anonymous(),
            tx_id: "in-tx".to_string(),
        };
        let e_out = UnifiedEvent {
            chain: "CkBTC".to_string(),
            timestamp: 0,
            direction: Direction::Out,
            amount_e8s: 500,
            counterparty: Principal::anonymous(),
            tx_id: "out-tx".to_string(),
        };
        assert_eq!(e_in.direction, Direction::In);
        assert_eq!(e_out.direction, Direction::Out);
    }

    // --- EngineHealthStatus --------------------------------------------------

    #[test]
    fn test_engine_health_status_structure() {
        let hs = EngineHealthStatus {
            cycle_balance: 1_000_000_000_000,
            last_tick: 42,
            is_running: true,
            watermark_count: 3,
        };
        assert!(hs.is_running);
        assert_eq!(hs.watermark_count, 3);
        assert!(hs.cycle_balance > 0);
    }

    // --- Timer mock ----------------------------------------------------------

    #[test]
    fn test_timer_initialization_flag() {
        // Simulate what init() does to the IS_RUNNING flag
        IS_RUNNING.with(|r| *r.borrow_mut() = true);
        let running = IS_RUNNING.with(|r| *r.borrow());
        assert!(running);
    }

    // --- LastTick stored/retrieved -------------------------------------------

    #[test]
    fn test_last_tick_roundtrip() {
        let lt = LastTick { value: 123_456_789 };
        let bytes = lt.to_bytes();
        let lt2 = LastTick::from_bytes(bytes);
        assert_eq!(lt2.value, 123_456_789);
    }

    // --- H3: Transaction deduplication tests ---------------------------------

    #[test]
    fn test_seen_tx_ids_key_uses_0xfe_sentinel() {
        let p = Principal::from_slice(&[1u8; 29]);
        let key = seen_tx_ids_key(&p);
        assert_eq!(key.0[29], 0xFE);
    }

    #[test]
    fn test_seen_tx_ids_key_differs_from_user_events_key() {
        let p = Principal::from_slice(&[1u8; 29]);
        let seen_key = seen_tx_ids_key(&p);
        let events_key = user_events_key(&p);
        assert_ne!(seen_key, events_key);
    }

    #[test]
    fn test_btreemap_dedup_logic() {
        // Verify BTreeMap correctly deduplicates tx IDs (second insert overwrites)
        let mut seen: BTreeMap<String, u64> = BTreeMap::new();
        seen.insert("tx-1".to_string(), 1000);
        seen.insert("tx-2".to_string(), 2000);
        seen.insert("tx-1".to_string(), 3000); // overwrite, not duplicate

        assert_eq!(seen.len(), 2);
        assert!(seen.contains_key("tx-1"));
        assert!(seen.contains_key("tx-2"));
    }

    #[test]
    fn test_seen_tx_ids_ttl_eviction() {
        // Entries older than 24h should be pruned
        const TTL_NS: u64 = 86_400 * 1_000_000_000;
        let now_ns: u64 = 200_000 * 1_000_000_000; // arbitrary "now"

        let mut seen: BTreeMap<String, u64> = BTreeMap::new();
        // Old entry: created 25h ago (should be pruned)
        seen.insert("old-tx".to_string(), now_ns - TTL_NS - 1);
        // Recent entry: created 1h ago (should survive)
        seen.insert("new-tx".to_string(), now_ns - 3_600 * 1_000_000_000);

        // Apply TTL prune (same logic as store_user_events)
        seen.retain(|_, ts| now_ns.saturating_sub(*ts) < TTL_NS);

        assert_eq!(seen.len(), 1, "Only the recent tx should survive");
        assert!(!seen.contains_key("old-tx"));
        assert!(seen.contains_key("new-tx"));
    }

    #[test]
    fn test_seen_tx_ids_bounded_at_max() {
        // Verify that we can enforce the MAX_SEEN_TX_IDS_PER_USER fallback cap
        let now_ns = 1_000_000_000_000u64;
        let mut seen: BTreeMap<String, u64> = BTreeMap::new();
        for i in 0..MAX_SEEN_TX_IDS_PER_USER + 5 {
            seen.insert(format!("tx-{:05}", i), now_ns + i as u64);
        }
        // Apply fallback cap: remove oldest by timestamp
        if seen.len() > MAX_SEEN_TX_IDS_PER_USER {
            let mut by_age: Vec<(String, u64)> =
                seen.iter().map(|(k, &v)| (k.clone(), v)).collect();
            by_age.sort_by_key(|(_, ts)| *ts);
            let to_remove = by_age.len() - MAX_SEEN_TX_IDS_PER_USER;
            for (k, _) in by_age.into_iter().take(to_remove) {
                seen.remove(&k);
            }
        }
        assert_eq!(seen.len(), MAX_SEEN_TX_IDS_PER_USER);
    }

    // =========================================================================
    // Phase 2c: Config Canister Sync + Per-User Channel Routing Tests
    // =========================================================================

    mod phase2c_tests {
        use super::*;
        use crate::delivery::AlertChannel;

        // -----------------------------------------------------------------------
        // UserChannelEntry storable roundtrip
        // -----------------------------------------------------------------------

        #[test]
        fn test_user_channel_entry_default_is_empty() {
            let entry = UserChannelEntry::default();
            assert!(entry.channels.is_empty());
            assert_eq!(entry.cached_at, 0);
        }

        #[test]
        fn test_user_channel_entry_storable_roundtrip() {
            let entry = UserChannelEntry {
                channels: vec![
                    AlertChannel::Discord { webhook_url: "https://discord.com/hook/1".to_string() },
                    AlertChannel::Slack { webhook_url: "https://hooks.slack.com/T0/B1/x".to_string() },
                ],
                cached_at: 1_700_000_000_000_000_000,
            };
            let bytes = entry.to_bytes();
            let entry2 = UserChannelEntry::from_bytes(bytes);
            assert_eq!(entry2.channels.len(), 2);
            assert_eq!(entry2.cached_at, 1_700_000_000_000_000_000);
        }

        #[test]
        fn test_user_channel_entry_storable_empty_channels() {
            let entry = UserChannelEntry { channels: vec![], cached_at: 999 };
            let entry2 = UserChannelEntry::from_bytes(entry.to_bytes());
            assert!(entry2.channels.is_empty());
            assert_eq!(entry2.cached_at, 999);
        }

        #[test]
        fn test_user_channel_entry_all_channel_types() {
            let entry = UserChannelEntry {
                channels: vec![
                    AlertChannel::Discord { webhook_url: "https://discord.com/hook".to_string() },
                    AlertChannel::Slack { webhook_url: "https://slack.com/hook".to_string() },
                    AlertChannel::Webhook { url: "https://example.com/hook".to_string(), secret: Some("s3cr3t".to_string()) },
                    AlertChannel::Email { address: "a@b.com".to_string(), api_url: "https://api.mg.net/v3/msgs".to_string(), api_key: "key-x".to_string() },
                ],
                cached_at: 42,
            };
            let entry2 = UserChannelEntry::from_bytes(entry.to_bytes());
            assert_eq!(entry2.channels.len(), 4);
        }

        // -----------------------------------------------------------------------
        // Cache TTL constant
        // -----------------------------------------------------------------------

        #[test]
        fn test_channel_cache_ttl_is_5_minutes_in_ns() {
            // 5 minutes = 300 seconds = 300_000_000_000 nanoseconds
            assert_eq!(CHANNEL_CACHE_TTL_NS, 300 * 1_000_000_000);
        }

        // -----------------------------------------------------------------------
        // Cache helper: get_cached_channels / store_cached_channels
        // -----------------------------------------------------------------------

        #[test]
        fn test_get_cached_channels_returns_none_when_empty() {
            let user = Principal::from_slice(&[201u8; 29]);
            let now_ns = 1_000_000_000_000u64;
            let result = get_cached_channels(&user, now_ns);
            assert!(result.is_none(), "Empty cache should return None");
        }

        #[test]
        fn test_store_and_get_cached_channels_fresh_entry() {
            let user = Principal::from_slice(&[202u8; 29]);
            let now_ns = 2_000_000_000_000u64;
            let channels = vec![
                AlertChannel::Discord { webhook_url: "https://discord.com/hook/202".to_string() },
            ];
            store_cached_channels(&user, channels.clone(), now_ns);

            let retrieved = get_cached_channels(&user, now_ns);
            assert!(retrieved.is_some(), "Should retrieve freshly cached entry");
            assert_eq!(retrieved.unwrap().len(), 1);
        }

        #[test]
        fn test_fetch_user_channels_cache_invalidation() {
            // Store an entry, then check it as expired (now_ns > cached_at + TTL)
            let user = Principal::from_slice(&[203u8; 29]);
            let cached_at = 5_000_000_000_000u64;
            let channels = vec![
                AlertChannel::Slack { webhook_url: "https://hooks.slack.com/x".to_string() },
            ];
            store_cached_channels(&user, channels, cached_at);

            // Query with now_ns = cached_at + TTL + 1 (expired)
            let expired_now = cached_at + CHANNEL_CACHE_TTL_NS + 1;
            let result = get_cached_channels(&user, expired_now);
            assert!(result.is_none(), "Expired cache entry should return None");
        }

        #[test]
        fn test_cache_still_valid_at_exactly_ttl_minus_1() {
            let user = Principal::from_slice(&[204u8; 29]);
            let cached_at = 10_000_000_000_000u64;
            let channels = vec![
                AlertChannel::Webhook { url: "https://example.com/wh".to_string(), secret: None },
            ];
            store_cached_channels(&user, channels, cached_at);

            // Query at cached_at + TTL - 1 (still valid)
            let near_expiry = cached_at + CHANNEL_CACHE_TTL_NS - 1;
            let result = get_cached_channels(&user, near_expiry);
            assert!(result.is_some(), "Cache entry should still be valid at TTL - 1ns");
        }

        #[test]
        fn test_cache_expired_exactly_at_ttl() {
            let user = Principal::from_slice(&[205u8; 29]);
            let cached_at = 20_000_000_000_000u64;
            let channels = vec![
                AlertChannel::Email {
                    address: "user@test.com".to_string(),
                    api_url: "https://api.mg.net/msg".to_string(),
                    api_key: "k".to_string(),
                },
            ];
            store_cached_channels(&user, channels, cached_at);

            // Query at exactly cached_at + TTL (expired — saturating_sub equals TTL, not < TTL)
            let exactly_ttl = cached_at + CHANNEL_CACHE_TTL_NS;
            let result = get_cached_channels(&user, exactly_ttl);
            assert!(result.is_none(), "Cache should be expired when age == TTL");
        }

        #[test]
        fn test_store_channels_overwrites_previous_entry() {
            let user = Principal::from_slice(&[206u8; 29]);
            let now_ns = 30_000_000_000_000u64;

            store_cached_channels(
                &user,
                vec![AlertChannel::Discord { webhook_url: "https://a.com".to_string() }],
                now_ns,
            );
            store_cached_channels(
                &user,
                vec![
                    AlertChannel::Slack { webhook_url: "https://b.com".to_string() },
                    AlertChannel::Slack { webhook_url: "https://c.com".to_string() },
                ],
                now_ns + 1,
            );

            let result = get_cached_channels(&user, now_ns + 1).unwrap();
            assert_eq!(result.len(), 2, "Overwrite should replace, not append");
            assert!(matches!(result[0], AlertChannel::Slack { .. }));
        }

        #[test]
        fn test_channel_cache_len_increments() {
            let before = channel_cache_len();
            let user = Principal::from_slice(&[207u8; 29]);
            store_cached_channels(&user, vec![], 1_000_000);
            let after = channel_cache_len();
            assert!(after >= before, "Cache len should not decrease after insert");
        }

        // -----------------------------------------------------------------------
        // No channels configured — skip logic
        // -----------------------------------------------------------------------

        #[test]
        fn test_no_channels_configured_skips_delivery() {
            // When a user has no cached channels and cache is empty → result is empty vec
            let user = Principal::from_slice(&[208u8; 29]);
            let now_ns = 1_000_000u64;
            // Explicitly store empty channels
            store_cached_channels(&user, vec![], now_ns);

            let channels = get_cached_channels(&user, now_ns).unwrap_or_default();
            assert!(channels.is_empty(), "No channels should mean delivery is skipped");
        }

        #[test]
        fn test_delivery_to_multiple_channels_routing() {
            // Verify that a user with 3 channels would have delivery called 3 times.
            // (Simulated — we count channels, actual HTTP outcalls require IC runtime)
            let user = Principal::from_slice(&[209u8; 29]);
            let now_ns = 1_000_000u64;
            let channels = vec![
                AlertChannel::Discord { webhook_url: "https://discord.com/h1".to_string() },
                AlertChannel::Slack   { webhook_url: "https://slack.com/h2".to_string() },
                AlertChannel::Webhook { url: "https://example.com/h3".to_string(), secret: None },
            ];
            store_cached_channels(&user, channels.clone(), now_ns);

            let retrieved = get_cached_channels(&user, now_ns).unwrap();
            assert_eq!(retrieved.len(), 3, "All 3 channels should be returned for routing");
        }

        // -----------------------------------------------------------------------
        // Inter-canister retry logic (unit-level simulation)
        // -----------------------------------------------------------------------

        #[test]
        fn test_inter_canister_call_retry_on_transient_error() {
            // Simulate retry counter: after 3 failures, we give up.
            let max_retries = 3u32;
            let mut attempts = 0u32;

            // Simulate 3 transient failures
            while attempts < max_retries {
                attempts += 1;
                // Each attempt: transient error
                let is_transient = true;
                if is_transient && attempts < max_retries {
                    // retry
                    continue;
                }
                break;
            }

            assert_eq!(attempts, max_retries, "Should attempt exactly {} times", max_retries);
        }

        #[test]
        fn test_retry_stops_after_max_attempts() {
            let max_retries = 3u32;
            let mut attempt_count = 0u32;
            let mut succeeded = false;

            for _attempt in 0..max_retries {
                attempt_count += 1;
                // Simulate persistent failure
                if false { // never succeeds
                    succeeded = true;
                    break;
                }
            }

            assert_eq!(attempt_count, max_retries);
            assert!(!succeeded, "Should not succeed when all attempts fail");
        }

        #[test]
        fn test_retry_succeeds_on_second_attempt() {
            let max_retries = 3u32;
            let mut attempt_count = 0u32;
            let mut succeeded = false;

            for attempt in 0..max_retries {
                attempt_count += 1;
                if attempt == 1 {
                    // Second attempt succeeds
                    succeeded = true;
                    break;
                }
            }

            assert!(succeeded);
            assert_eq!(attempt_count, 2, "Should succeed on attempt 2");
        }

        // -----------------------------------------------------------------------
        // Alert routing edge cases
        // -----------------------------------------------------------------------

        #[test]
        fn test_different_users_have_independent_channel_caches() {
            let user_a = Principal::from_slice(&[210u8; 29]);
            let user_b = Principal::from_slice(&[211u8; 29]);
            let now_ns = 5_000_000u64;

            store_cached_channels(
                &user_a,
                vec![AlertChannel::Discord { webhook_url: "https://a.com".to_string() }],
                now_ns,
            );
            store_cached_channels(
                &user_b,
                vec![
                    AlertChannel::Slack { webhook_url: "https://b1.com".to_string() },
                    AlertChannel::Slack { webhook_url: "https://b2.com".to_string() },
                ],
                now_ns,
            );

            let a_channels = get_cached_channels(&user_a, now_ns).unwrap();
            let b_channels = get_cached_channels(&user_b, now_ns).unwrap();
            assert_eq!(a_channels.len(), 1);
            assert_eq!(b_channels.len(), 2);
        }

        #[test]
        fn test_cache_key_is_principal_text() {
            // Verify that two principals with different bytes produce different keys
            let p1 = Principal::from_slice(&[212u8; 29]);
            let p2 = Principal::from_slice(&[213u8; 29]);
            assert_ne!(p1.to_text(), p2.to_text());
        }

        #[test]
        fn test_empty_channel_list_cached_separately() {
            let user = Principal::from_slice(&[214u8; 29]);
            let now_ns = 8_000_000u64;
            store_cached_channels(&user, vec![], now_ns);

            let result = get_cached_channels(&user, now_ns);
            assert!(result.is_some(), "Empty channel list is a valid cache entry");
            assert!(result.unwrap().is_empty());
        }

        #[test]
        fn test_cache_with_five_channels_max() {
            // Config canister allows max 5 channels per user
            let user = Principal::from_slice(&[215u8; 29]);
            let now_ns = 9_000_000u64;
            let channels = (0..5).map(|i| AlertChannel::Discord {
                webhook_url: format!("https://discord.com/hook/{}", i),
            }).collect::<Vec<_>>();
            store_cached_channels(&user, channels, now_ns);

            let result = get_cached_channels(&user, now_ns).unwrap();
            assert_eq!(result.len(), 5);
        }

        #[test]
        fn test_alert_not_sent_when_all_channels_fail() {
            // Simulate: 2 channels, both fail → mark as retried or failed_perm
            let outcomes = vec![
                crate::delivery::DeliveryOutcome::TransportError { message: "timeout".to_string() },
                crate::delivery::DeliveryOutcome::TransportError { message: "timeout".to_string() },
            ];
            let any_success = outcomes.iter().any(|o| o.is_success());
            let any_permanent = outcomes.iter().any(|o| o.is_permanent_failure());
            assert!(!any_success);
            assert!(!any_permanent); // transport errors are transient
        }

        #[test]
        fn test_alert_sent_when_at_least_one_channel_succeeds() {
            // Simulate: channel 1 fails, channel 2 succeeds → any_success = true
            let outcomes = vec![
                crate::delivery::DeliveryOutcome::TransportError { message: "timeout".to_string() },
                crate::delivery::DeliveryOutcome::Success { status: 200 },
            ];
            let any_success = outcomes.iter().any(|o| o.is_success());
            assert!(any_success, "Should mark sent if at least one channel succeeds");
        }

        #[test]
        fn test_channel_cache_ttl_boundary_just_before_expiry() {
            let cached_at = 100_000_000_000u64;
            let age = CHANNEL_CACHE_TTL_NS - 1;
            let now_ns = cached_at + age;
            // is_fresh = now_ns.saturating_sub(cached_at) < TTL
            let is_fresh = now_ns.saturating_sub(cached_at) < CHANNEL_CACHE_TTL_NS;
            assert!(is_fresh, "1ns before TTL should still be fresh");
        }

        #[test]
        fn test_channel_cache_ttl_boundary_at_expiry() {
            let cached_at = 100_000_000_000u64;
            let now_ns = cached_at + CHANNEL_CACHE_TTL_NS;
            let is_fresh = now_ns.saturating_sub(cached_at) < CHANNEL_CACHE_TTL_NS;
            assert!(!is_fresh, "At TTL exactly should be expired");
        }
    }

    // =========================================================================
    // Phase 1d: Detection Engine Tests
    // =========================================================================
    mod detector_tests {
        use super::*;
        use crate::detector::{
            evaluate, rule_a1_large_transfer, rule_a3_rapid_transactions, rule_a4_new_address,
            DetectionContext, Severity,
        };

        fn make_out_event(amount: u128, counterparty: Principal, ts: u64) -> UnifiedEvent {
            UnifiedEvent {
                chain: "ICP".to_string(),
                timestamp: ts,
                direction: Direction::Out,
                amount_e8s: amount,
                counterparty,
                tx_id: format!("tx-{}", ts),
            }
        }

        fn make_in_event(amount: u128, ts: u64) -> UnifiedEvent {
            UnifiedEvent {
                chain: "ICP".to_string(),
                timestamp: ts,
                direction: Direction::In,
                amount_e8s: amount,
                counterparty: Principal::anonymous(),
                tx_id: format!("in-{}", ts),
            }
        }

        // --- A1: Large transfer ---

        #[test]
        fn test_a1_large_transfer_detected() {
            let events = vec![make_out_event(60, Principal::anonymous(), 1000)];
            let result = rule_a1_large_transfer(&events, 100);
            assert!(result.is_some());
            assert_eq!(result.unwrap().rule_id, "A1");
        }

        #[test]
        fn test_a1_small_transfer_ignored() {
            let events = vec![make_out_event(40, Principal::anonymous(), 1000)];
            let result = rule_a1_large_transfer(&events, 100);
            assert!(result.is_none());
        }

        #[test]
        fn test_a1_exactly_50_percent_not_triggered() {
            // 50/100 = 50%, threshold is > 50% so exactly 50 should NOT trigger
            let events = vec![make_out_event(50, Principal::anonymous(), 1000)];
            let result = rule_a1_large_transfer(&events, 100);
            assert!(result.is_none(), "Exactly 50% should not trigger A1");
        }

        #[test]
        fn test_a1_51_percent_triggered() {
            // 51/100 = 51% — should trigger
            let events = vec![make_out_event(51, Principal::anonymous(), 1000)];
            let result = rule_a1_large_transfer(&events, 100);
            assert!(result.is_some(), "51% should trigger A1");
        }

        #[test]
        fn test_a1_zero_balance_no_trigger() {
            let events = vec![make_out_event(100, Principal::anonymous(), 1000)];
            let result = rule_a1_large_transfer(&events, 0);
            assert!(result.is_none(), "Zero balance should not trigger A1");
        }

        #[test]
        fn test_a1_incoming_tx_not_triggered() {
            let events = vec![make_in_event(999, 1000)];
            let result = rule_a1_large_transfer(&events, 100);
            assert!(result.is_none());
        }

        #[test]
        fn test_a1_weight_is_7() {
            let events = vec![make_out_event(51, Principal::anonymous(), 1000)];
            let m = rule_a1_large_transfer(&events, 100).unwrap();
            assert_eq!(m.weight, 7);
        }

        // --- A3: Rapid transactions ---

        fn make_n_out_events(n: usize, start_ts: u64, interval_ns: u64) -> Vec<UnifiedEvent> {
            (0..n)
                .map(|i| make_out_event(1, Principal::anonymous(), start_ts + i as u64 * interval_ns))
                .collect()
        }

        #[test]
        fn test_a3_five_txs_not_triggered() {
            // Exactly 5 outgoing txs in 10 min — should NOT trigger (threshold is >5)
            let events = make_n_out_events(5, 0, 60_000_000_000); // 1 min apart
            let result = rule_a3_rapid_transactions(&events);
            assert!(result.is_none(), "5 txs should not trigger A3");
        }

        #[test]
        fn test_a3_six_txs_triggered() {
            // 6 txs within 10 min — should trigger
            let events = make_n_out_events(6, 0, 60_000_000_000); // 1 min apart, total 5 min
            let result = rule_a3_rapid_transactions(&events);
            assert!(result.is_some(), "6 txs in 10 min should trigger A3");
        }

        #[test]
        fn test_a3_six_txs_outside_10min_not_triggered() {
            // 6 txs but spaced so no 6 fit within 10 min window
            let min = 60_000_000_000u64;
            let events = make_n_out_events(6, 0, 2 * min + 1); // slightly over 2 min apart → 10min+5s span
            let result = rule_a3_rapid_transactions(&events);
            assert!(result.is_none(), "6 txs spanning >10 min should not trigger A3");
        }

        #[test]
        fn test_a3_weight_is_3() {
            let events = make_n_out_events(6, 0, 60_000_000_000);
            let m = rule_a3_rapid_transactions(&events).unwrap();
            assert_eq!(m.weight, 3);
        }

        #[test]
        fn test_a3_empty_events_not_triggered() {
            let result = rule_a3_rapid_transactions(&[]);
            assert!(result.is_none());
        }

        #[test]
        fn test_a3_incoming_txs_not_counted() {
            // 10 incoming txs — should not trigger (only outgoing counted)
            let events: Vec<UnifiedEvent> = (0..10)
                .map(|i| make_in_event(1, i * 60_000_000_000))
                .collect();
            let result = rule_a3_rapid_transactions(&events);
            assert!(result.is_none());
        }

        // --- A4: New destination address ---

        #[test]
        fn test_a4_known_address_not_triggered() {
            let p = Principal::from_slice(&[42u8; 29]);
            let events = vec![make_out_event(100, p, 1000)];
            let allowlist = vec![p.to_text()];
            let result = rule_a4_new_address(&events, &allowlist);
            assert!(result.is_none());
        }

        #[test]
        fn test_a4_unknown_address_triggered() {
            let p = Principal::from_slice(&[42u8; 29]);
            let events = vec![make_out_event(100, p, 1000)];
            let allowlist: Vec<String> = vec![];
            let result = rule_a4_new_address(&events, &allowlist);
            assert!(result.is_some(), "Unknown address should trigger A4");
        }

        #[test]
        fn test_a4_weight_is_1() {
            let p = Principal::from_slice(&[1u8; 29]);
            let events = vec![make_out_event(100, p, 1000)];
            let m = rule_a4_new_address(&events, &[]).unwrap();
            assert_eq!(m.weight, 1);
        }

        #[test]
        fn test_a4_incoming_ignored() {
            let events = vec![make_in_event(100, 1000)];
            let result = rule_a4_new_address(&events, &[]);
            assert!(result.is_none());
        }

        #[test]
        fn test_a4_empty_events_not_triggered() {
            let result = rule_a4_new_address(&[], &[]);
            assert!(result.is_none());
        }

        // --- Scoring ---

        fn make_ctx<'a>(
            events: &'a [UnifiedEvent],
            balance: u128,
            allowlist: &'a [String],
            threshold: u8,
        ) -> DetectionContext<'a> {
            DetectionContext {
                events,
                estimated_balance_e8s: balance,
                balance_e8s: None,
                allowlisted_addresses: allowlist,
                alert_threshold: threshold,
            }
        }

        #[test]
        fn test_score_a1_only_equals_7() {
            // A1 only: large transfer, no rapid txs (only 1 tx), known address
            let p = Principal::from_slice(&[7u8; 29]);
            let events = vec![make_out_event(51, p, 1000)];
            let allowlist = vec![p.to_text()];
            let ctx = make_ctx(&events, 100, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 7);
            assert_eq!(result.rules_triggered.len(), 1);
            assert_eq!(result.rules_triggered[0].rule_id, "A1");
        }

        #[test]
        fn test_score_a3_only_equals_3() {
            // 6 outgoing in 10 min, all going to same known address, small amounts
            let p = Principal::from_slice(&[8u8; 29]);
            let allowlist = vec![p.to_text()];
            let events = make_n_out_events(6, 0, 60_000_000_000)
                .into_iter()
                .map(|mut e| { e.counterparty = p; e })
                .collect::<Vec<_>>();
            // Balance large enough that no single tx > 50%
            let ctx = make_ctx(&events, 1_000_000, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 3);
        }

        #[test]
        fn test_score_a1_plus_a3_equals_10() {
            let p = Principal::from_slice(&[9u8; 29]);
            let allowlist = vec![p.to_text()];
            // 6 txs in 10 min, one is large (>50% of balance)
            let mut events = make_n_out_events(6, 0, 60_000_000_000)
                .into_iter()
                .map(|mut e| { e.counterparty = p; e.amount_e8s = 1; e })
                .collect::<Vec<_>>();
            // Override first to be large
            events[0].amount_e8s = 51;
            let ctx = make_ctx(&events, 100, &allowlist, 7);
            let result = evaluate(&ctx);
            // A1(7) + A3(3) = 10
            assert_eq!(result.score, 10);
        }

        // --- Threshold / should_alert ---

        #[test]
        fn test_threshold_score_equals_threshold_alerts() {
            // score 7, threshold 7 → should_alert = true
            let p = Principal::from_slice(&[10u8; 29]);
            let events = vec![make_out_event(51, p, 1000)];
            let allowlist = vec![p.to_text()];
            let ctx = make_ctx(&events, 100, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 7);
            assert!(result.should_alert);
        }

        #[test]
        fn test_threshold_score_below_threshold_no_alert() {
            // score 3, threshold 7 → should_alert = false
            let p = Principal::from_slice(&[11u8; 29]);
            let allowlist = vec![p.to_text()];
            let events = make_n_out_events(6, 0, 60_000_000_000)
                .into_iter()
                .map(|mut e| { e.counterparty = p; e })
                .collect::<Vec<_>>();
            let ctx = make_ctx(&events, 1_000_000, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 3);
            assert!(!result.should_alert);
        }

        #[test]
        fn test_no_rules_triggered() {
            // No events → no rules triggered, score 0
            let ctx = make_ctx(&[], 1000, &[], 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 0);
            assert!(result.rules_triggered.is_empty());
            assert!(!result.should_alert);
        }

        // --- Severity enum ---

        #[test]
        fn test_severity_from_score_info() {
            assert_eq!(Severity::from_score(0), Severity::Info);
            assert_eq!(Severity::from_score(2), Severity::Info);
        }

        #[test]
        fn test_severity_from_score_warn() {
            assert_eq!(Severity::from_score(3), Severity::Warn);
            assert_eq!(Severity::from_score(6), Severity::Warn);
        }

        #[test]
        fn test_severity_from_score_critical() {
            assert_eq!(Severity::from_score(7), Severity::Critical);
            assert_eq!(Severity::from_score(14), Severity::Critical);
        }

        #[test]
        fn test_severity_from_score_emergency() {
            assert_eq!(Severity::from_score(15), Severity::Emergency);
            assert_eq!(Severity::from_score(255), Severity::Emergency);
        }

        // --- Alert payload ---

        #[test]
        fn test_alert_payload_fields_populated() {
            use crate::alerts::format_alert;
            let p = Principal::from_slice(&[20u8; 29]);
            let dest = Principal::from_slice(&[21u8; 29]);
            // Put dest in allowlist so A4 doesn't fire, only A1 (score=7)
            let allowlist = vec![dest.to_text()];
            let events = vec![make_out_event(51, dest, 1000)];
            let ctx = make_ctx(&events, 100, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 7, "Expected only A1 to fire");
            let payload = format_alert(p, result, events, 1_700_000_000_000_000_000u64);
            assert!(!payload.alert_id.is_empty());
            assert_eq!(payload.user, p);
            assert_eq!(payload.severity, "CRITICAL");
            assert_eq!(payload.severity_score, 7);
            assert!(!payload.rules_triggered.is_empty());
            assert!(!payload.events_summary.is_empty());
            assert!(!payload.recommended_action.is_empty());
        }

        #[test]
        fn test_alert_payload_no_events_summary() {
            use crate::alerts::format_alert;
            let p = Principal::from_slice(&[21u8; 29]);
            // Manually build a result with should_alert true but no events
            let result = crate::detector::DetectionResult {
                score: 7,
                severity: Severity::Critical,
                rules_triggered: vec![crate::detector::RuleMatch {
                    rule_id: "A1".to_string(),
                    description: "test".to_string(),
                    weight: 7,
                }],
                should_alert: true,
            };
            let payload = format_alert(p, result, vec![], 1000);
            assert_eq!(payload.events_summary, "No events");
        }

        // --- Edge cases ---

        #[test]
        fn test_a1_empty_events() {
            let result = rule_a1_large_transfer(&[], 1000);
            assert!(result.is_none());
        }

        #[test]
        fn test_a3_four_txs_not_triggered() {
            let events = make_n_out_events(4, 0, 60_000_000_000);
            assert!(rule_a3_rapid_transactions(&events).is_none());
        }

        #[test]
        fn test_evaluate_all_three_rules() {
            // A1 + A3 + A4 all triggered → score 11
            let unknown = Principal::from_slice(&[99u8; 29]);
            let mut events = make_n_out_events(6, 0, 60_000_000_000)
                .into_iter()
                .map(|mut e| { e.counterparty = unknown; e.amount_e8s = 1; e })
                .collect::<Vec<_>>();
            events[0].amount_e8s = 51; // trigger A1
            let allowlist: Vec<String> = vec![];
            let ctx = make_ctx(&events, 100, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 11); // A1(7)+A3(3)+A4(1)
            assert!(result.should_alert);
            assert_eq!(result.severity, Severity::Critical);
        }
    }
}
