pub mod alerts;
pub mod canisters;
pub mod detector;
pub mod fetcher;
pub mod icrc;
#[cfg(test)]
mod integration_tests;

use candid::{CandidType, Deserialize, Principal};
use ic_cdk::{api, caller, init, query, update};
use ic_stable_structures::storable::Bound;
use ic_stable_structures::{DefaultMemoryImpl, StableBTreeMap, Storable};
use serde::Serialize;
use std::borrow::Cow;
use std::cell::RefCell;

use alerts::format_alert;
use canisters::MAX_EVENTS_PER_USER;
use detector::{evaluate, DetectionContext};
use fetcher::{merge_into_ring_buffer, update_watermark_after_fetch};
use icrc::IcrcAccount;

// ---------------------------------------------------------------------------
// Security constants
// ---------------------------------------------------------------------------
const MIN_CYCLE_BALANCE: u64 = 500_000_000_000; // 500B cycles – cycle drain guard
#[cfg(test)]
pub const MIN_CYCLE_BALANCE_PUB: u64 = MIN_CYCLE_BALANCE;

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

#[derive(CandidType, Deserialize, Serialize, Clone, Debug, PartialEq)]
pub enum Chain {
    ICP,
    CkBTC,
    CkETH,
}

impl Chain {
    /// Return a stable u8 discriminant for use as a BTreeMap key byte.
    pub fn discriminant(&self) -> u8 {
        match self {
            Chain::ICP => 0,
            Chain::CkBTC => 1,
            Chain::CkETH => 2,
        }
    }

    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Chain::ICP),
            1 => Some(Chain::CkBTC),
            2 => Some(Chain::CkETH),
            _ => None,
        }
    }
}

#[derive(CandidType, Deserialize, Serialize, Clone, Debug, PartialEq)]
pub enum Direction {
    In,
    Out,
}

#[derive(CandidType, Deserialize, Serialize, Clone, Debug, PartialEq)]
pub enum AlertStatus {
    Pending,
    Sent,
    Failed,
}

// ---------------------------------------------------------------------------
// Core data structures
// ---------------------------------------------------------------------------

/// Normalised transaction event across all monitored chains.
#[derive(CandidType, Deserialize, Serialize, Clone, Debug)]
pub struct UnifiedEvent {
    pub chain: String,
    pub timestamp: u64,
    pub direction: Direction,
    pub amount_e8s: u64,
    pub counterparty: Principal,
    pub tx_id: String,
}

/// Record of an alert that was generated by the engine.
#[derive(CandidType, Deserialize, Serialize, Clone, Debug)]
pub struct AlertRecord {
    pub alert_id: String,
    pub timestamp: u64,
    pub user: Principal,
    pub rules_triggered: Vec<String>,
    pub severity: u8,
    pub status: AlertStatus,
}

impl Storable for AlertRecord {
    fn to_bytes(&self) -> Cow<[u8]> {
        Cow::Owned(candid::encode_one(self).unwrap())
    }
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        candid::decode_one(&bytes).unwrap()
    }
    const BOUND: Bound = Bound::Unbounded;
}

/// Per-chain polling watermark stored in stable memory.
#[derive(CandidType, Deserialize, Serialize, Clone, Debug, Default)]
pub struct Watermark {
    pub last_tx_id: String,
    pub last_checked: u64,
    pub block_height: u64,
}

impl Storable for Watermark {
    fn to_bytes(&self) -> Cow<[u8]> {
        Cow::Owned(candid::encode_one(self).unwrap())
    }
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        candid::decode_one(&bytes).unwrap()
    }
    const BOUND: Bound = Bound::Unbounded;
}

/// Stable-memory key for the watermark map: (principal bytes + chain discriminant).
/// We encode as a 30-byte fixed array: 29 bytes principal + 1 byte chain.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct WatermarkKey(pub [u8; 30]);

impl WatermarkKey {
    pub fn new(principal: &Principal, chain: &Chain) -> Self {
        let pb = principal.as_slice();
        let mut key = [0u8; 30];
        let len = pb.len().min(29);
        key[..len].copy_from_slice(&pb[..len]);
        key[29] = chain.discriminant();
        WatermarkKey(key)
    }
}

impl Storable for WatermarkKey {
    fn to_bytes(&self) -> Cow<[u8]> {
        Cow::Owned(self.0.to_vec())
    }
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        let mut arr = [0u8; 30];
        let len = bytes.len().min(30);
        arr[..len].copy_from_slice(&bytes[..len]);
        WatermarkKey(arr)
    }
    const BOUND: Bound = Bound::Bounded { max_size: 30, is_fixed_size: true };
}

/// Tiny wrapper for last_tick stored in stable memory.
#[derive(CandidType, Deserialize, Serialize, Clone, Debug, Default)]
struct LastTick {
    pub value: u64,
}

impl Storable for LastTick {
    fn to_bytes(&self) -> Cow<[u8]> {
        Cow::Owned(candid::encode_one(self).unwrap())
    }
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        candid::decode_one(&bytes).unwrap()
    }
    const BOUND: Bound = Bound::Unbounded;
}

/// Wrapper for config canister principal stored in stable memory.
#[derive(CandidType, Deserialize, Serialize, Clone, Debug, Default)]
struct StoredPrincipal {
    pub value: Option<Principal>,
}

impl Storable for StoredPrincipal {
    fn to_bytes(&self) -> Cow<[u8]> {
        Cow::Owned(candid::encode_one(self).unwrap())
    }
    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        candid::decode_one(&bytes).unwrap()
    }
    const BOUND: Bound = Bound::Unbounded;
}

// ---------------------------------------------------------------------------
// Health response type
// ---------------------------------------------------------------------------

#[derive(CandidType, Deserialize, Serialize, Clone, Debug)]
pub struct EngineHealthStatus {
    pub cycle_balance: u64,
    pub last_tick: u64,
    pub is_running: bool,
    pub watermark_count: u64,
}

// ---------------------------------------------------------------------------
// Stable storage (thread-local)
// ---------------------------------------------------------------------------

/// Stable key used for the single-slot "last_tick" record.
const LAST_TICK_KEY: &str = "__last_tick__";
/// Stable key for config canister principal.
const CONFIG_CANISTER_KEY: &str = "__config_canister__";

thread_local! {
    /// Watermarks: (principal || chain_discriminant) → Watermark
    static WATERMARKS: RefCell<StableBTreeMap<WatermarkKey, Watermark, DefaultMemoryImpl>> =
        RefCell::new(StableBTreeMap::new(DefaultMemoryImpl::default()));

    /// Alert history: alert_id → AlertRecord
    static ALERTS: RefCell<StableBTreeMap<String, AlertRecord, DefaultMemoryImpl>> =
        RefCell::new(StableBTreeMap::new(DefaultMemoryImpl::default()));

    /// Single-slot metadata (last_tick, config canister id, …)
    static META: RefCell<StableBTreeMap<String, Vec<u8>, DefaultMemoryImpl>> =
        RefCell::new(StableBTreeMap::new(DefaultMemoryImpl::default()));

    /// Per-user event ring buffer: WatermarkKey (principal, ICP chain) → candid-encoded Vec<UnifiedEvent>
    /// We reuse WatermarkKey as a 30-byte principal key (chain byte = 0xFF for event store).
    static USER_EVENTS: RefCell<StableBTreeMap<WatermarkKey, Vec<u8>, DefaultMemoryImpl>> =
        RefCell::new(StableBTreeMap::new(DefaultMemoryImpl::default()));

    /// Runtime flag: has the timer been started?
    static IS_RUNNING: RefCell<bool> = RefCell::new(false);
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn get_last_tick() -> u64 {
    META.with(|m| {
        m.borrow()
            .get(&LAST_TICK_KEY.to_string())
            .and_then(|b| candid::decode_one::<LastTick>(&b).ok())
            .map(|lt| lt.value)
            .unwrap_or(0)
    })
}

fn set_last_tick(ts: u64) {
    META.with(|m| {
        let bytes = candid::encode_one(&LastTick { value: ts }).unwrap();
        m.borrow_mut().insert(LAST_TICK_KEY.to_string(), bytes);
    });
}

fn get_config_canister_id() -> Option<Principal> {
    META.with(|m| {
        m.borrow()
            .get(&CONFIG_CANISTER_KEY.to_string())
            .and_then(|b| candid::decode_one::<StoredPrincipal>(&b).ok())
            .and_then(|sp| sp.value)
    })
}

fn store_config_canister_id(id: Principal) {
    META.with(|m| {
        let bytes = candid::encode_one(&StoredPrincipal { value: Some(id) }).unwrap();
        m.borrow_mut().insert(CONFIG_CANISTER_KEY.to_string(), bytes);
    });
}

/// Cycle drain protection — panics (traps) if balance is critically low.
fn guard_cycles() {
    let balance = api::canister_balance();
    if balance < MIN_CYCLE_BALANCE {
        ic_cdk::trap(&format!(
            "Cycle drain guard: balance {} < minimum {}",
            balance, MIN_CYCLE_BALANCE
        ));
    }
}

/// Reject anonymous callers on update endpoints.
fn reject_anonymous() {
    if caller() == Principal::anonymous() {
        ic_cdk::trap("Anonymous callers are not permitted");
    }
}

// ---------------------------------------------------------------------------
// Timer
// ---------------------------------------------------------------------------

/// Called every 30 seconds by the IC timer.
fn timer_tick() {
    let ts = api::time();
    ic_cdk::println!("Guardian tick at {}", ts);

    // Cycle balance check (log only inside the timer — don't trap here)
    let balance = api::canister_balance();
    if balance < MIN_CYCLE_BALANCE {
        ic_cdk::println!(
            "WARNING: cycle balance {} below minimum {}",
            balance,
            MIN_CYCLE_BALANCE
        );
    }

    // Update health status
    set_last_tick(ts);

    // Phase 1c: spawn async fetch for all users (not in test builds — no ic_cdk runtime)
    #[cfg(not(test))]
    ic_cdk::spawn(async move {
        run_fetch_cycle(ts).await;
    });
}

/// Async fetch cycle: for each known watermark entry, fetch transactions from
/// all 3 chains, store new events in the ring buffer, and update watermarks.
#[cfg(not(test))]
async fn run_fetch_cycle(now_ns: u64) {
    // Collect all unique principals from the watermark map.
    let principals: Vec<Principal> = WATERMARKS.with(|w| {
        w.borrow()
            .iter()
            .map(|(key, _)| {
                // First 29 bytes of key encode the principal slice.
                let slice = &key.0[..29];
                // Strip trailing zero padding to reconstruct.
                let end = slice.iter().rposition(|&b| b != 0).map(|i| i + 1).unwrap_or(0);
                Principal::from_slice(&slice[..end])
            })
            .collect::<std::collections::HashSet<Principal>>()
            .into_iter()
            .collect()
    });

    for principal in principals {
        let account = IcrcAccount::new(principal);

        // Fetch ICP
        let icp_wm_key = WatermarkKey::new(&principal, &Chain::ICP);
        let icp_wm = WATERMARKS.with(|w| w.borrow().get(&icp_wm_key).unwrap_or_default());
        match fetcher::fetch_icp_transactions(account.clone(), &icp_wm).await {
            Ok(events) => {
                let mut updated_wm = icp_wm.clone();
                update_watermark_after_fetch(&mut updated_wm, &events, now_ns);
                WATERMARKS.with(|w| w.borrow_mut().insert(icp_wm_key, updated_wm));
                store_user_events(&principal, events);
            }
            Err(e) => ic_cdk::println!("ICP fetch error for {:?}: {}", principal, e),
        }

        // Fetch ckBTC
        let ckbtc_wm_key = WatermarkKey::new(&principal, &Chain::CkBTC);
        let ckbtc_wm = WATERMARKS.with(|w| w.borrow().get(&ckbtc_wm_key).unwrap_or_default());
        match fetcher::fetch_ckbtc_transactions(account.clone(), &ckbtc_wm).await {
            Ok(events) => {
                let mut updated_wm = ckbtc_wm.clone();
                update_watermark_after_fetch(&mut updated_wm, &events, now_ns);
                WATERMARKS.with(|w| w.borrow_mut().insert(ckbtc_wm_key, updated_wm));
                store_user_events(&principal, events);
            }
            Err(e) => ic_cdk::println!("ckBTC fetch error for {:?}: {}", principal, e),
        }

        // Fetch ckETH
        let cketh_wm_key = WatermarkKey::new(&principal, &Chain::CkETH);
        let cketh_wm = WATERMARKS.with(|w| w.borrow().get(&cketh_wm_key).unwrap_or_default());
        match fetcher::fetch_cketh_transactions(account.clone(), &cketh_wm).await {
            Ok(events) => {
                let mut updated_wm = cketh_wm.clone();
                update_watermark_after_fetch(&mut updated_wm, &events, now_ns);
                WATERMARKS.with(|w| w.borrow_mut().insert(cketh_wm_key, updated_wm));
                store_user_events(&principal, events);
            }
            Err(e) => ic_cdk::println!("ckETH fetch error for {:?}: {}", principal, e),
        }

        // --- Detection engine ---
        // Load all stored events for this user and run rule evaluation.
        let user_events = load_user_events(&principal);
        if !user_events.is_empty() {
            // Estimate balance: sum of incoming minus sum of outgoing (floor 0)
            let total_in: u64 = user_events.iter()
                .filter(|e| e.direction == Direction::In)
                .map(|e| e.amount_e8s)
                .fold(0u64, |a, x| a.saturating_add(x));
            let total_out: u64 = user_events.iter()
                .filter(|e| e.direction == Direction::Out)
                .map(|e| e.amount_e8s)
                .fold(0u64, |a, x| a.saturating_add(x));
            let estimated_balance = total_in.saturating_sub(total_out);

            // Default config values (Phase 2: fetch from config canister)
            let alert_threshold: u8 = 7;
            let allowlisted: Vec<String> = vec![];

            let ctx = DetectionContext {
                events: &user_events,
                estimated_balance_e8s: estimated_balance,
                allowlisted_addresses: &allowlisted,
                alert_threshold,
            };

            let result = evaluate(&ctx);

            if result.should_alert {
                let severity_str = result.severity.as_str().to_string();
                let payload = format_alert(principal, result, user_events, now_ns);
                ic_cdk::println!("ALERT: {} for {:?} (alert_id={})", severity_str, principal, payload.alert_id);
                // TODO Phase 2: HTTPS outcall to notify external channel
                // ic_cdk::println!("Placeholder: would send outcall for alert {}", payload.alert_id);
            }
        }
    }
}

/// Load all events stored for a user from stable memory.
fn load_user_events(principal: &Principal) -> Vec<UnifiedEvent> {
    let key = user_events_key(principal);
    USER_EVENTS.with(|ue| {
        ue.borrow()
            .get(&key)
            .and_then(|b| candid::decode_one::<Vec<UnifiedEvent>>(&b).ok())
            .unwrap_or_default()
    })
}

/// Merge `new_events` into the per-user ring buffer in stable memory.
fn store_user_events(principal: &Principal, new_events: Vec<UnifiedEvent>) {
    if new_events.is_empty() {
        return;
    }
    let key = user_events_key(principal);
    let mut existing: Vec<UnifiedEvent> = USER_EVENTS.with(|ue| {
        ue.borrow()
            .get(&key)
            .and_then(|b| candid::decode_one::<Vec<UnifiedEvent>>(&b).ok())
            .unwrap_or_default()
    });
    merge_into_ring_buffer(&mut existing, new_events, MAX_EVENTS_PER_USER);
    let encoded = candid::encode_one(&existing).unwrap_or_default();
    USER_EVENTS.with(|ue| ue.borrow_mut().insert(key, encoded));
}

/// Build a WatermarkKey used as the user-events ring-buffer key.
/// We use chain discriminant 0xFF to distinguish from watermark keys.
fn user_events_key(principal: &Principal) -> WatermarkKey {
    let pb = principal.as_slice();
    let mut key = [0u8; 30];
    let len = pb.len().min(29);
    key[..len].copy_from_slice(&pb[..len]);
    key[29] = 0xFF; // sentinel: not a real chain discriminant
    WatermarkKey(key)
}

// ---------------------------------------------------------------------------
// Canister lifecycle
// ---------------------------------------------------------------------------

#[init]
fn init() {
    // Start the 30-second heartbeat timer
    ic_cdk_timers::set_timer_interval(
        std::time::Duration::from_secs(30),
        timer_tick,
    );
    IS_RUNNING.with(|r| *r.borrow_mut() = true);
    ic_cdk::println!("Guardian Engine initialised");
}

// ---------------------------------------------------------------------------
// Query endpoints
// ---------------------------------------------------------------------------

#[query]
fn get_health() -> EngineHealthStatus {
    let cycle_balance = api::canister_balance();
    let last_tick = get_last_tick();
    let is_running = IS_RUNNING.with(|r| *r.borrow());
    let watermark_count = WATERMARKS.with(|w| w.borrow().len());

    EngineHealthStatus {
        cycle_balance,
        last_tick,
        is_running,
        watermark_count,
    }
}

// ---------------------------------------------------------------------------
// Update endpoints
// ---------------------------------------------------------------------------

/// Store the principal of the companion guardian_config canister.
#[update]
fn set_config_canister_id(id: Principal) {
    reject_anonymous();
    guard_cycles();
    store_config_canister_id(id);
    ic_cdk::println!("Config canister id set to {:?}", id);
}

/// Stub: fetch user configurations from the config canister.
#[allow(dead_code)]
async fn fetch_user_configs() {
    ic_cdk::println!("fetching configs");
    if let Some(config_id) = get_config_canister_id() {
        ic_cdk::println!("Config canister: {:?}", config_id);
        // TODO Phase 1c: inter-canister call to guardian_config
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // --- Watermark -----------------------------------------------------------

    #[test]
    fn test_watermark_default() {
        let w = Watermark::default();
        assert_eq!(w.last_tx_id, "");
        assert_eq!(w.last_checked, 0);
        assert_eq!(w.block_height, 0);
    }

    #[test]
    fn test_watermark_storable_roundtrip() {
        let w = Watermark {
            last_tx_id: "tx-abc-123".to_string(),
            last_checked: 1_709_000_000_000_000_000,
            block_height: 42_000,
        };
        let bytes = w.to_bytes();
        let w2 = Watermark::from_bytes(bytes);
        assert_eq!(w2.last_tx_id, "tx-abc-123");
        assert_eq!(w2.last_checked, 1_709_000_000_000_000_000);
        assert_eq!(w2.block_height, 42_000);
    }

    #[test]
    fn test_watermark_storable_empty_tx_id() {
        let w = Watermark {
            last_tx_id: String::new(),
            last_checked: 0,
            block_height: 0,
        };
        let w2 = Watermark::from_bytes(w.to_bytes());
        assert_eq!(w2.last_tx_id, "");
    }

    // --- WatermarkKey --------------------------------------------------------

    #[test]
    fn test_watermark_key_encoding() {
        let p = Principal::from_slice(&[1u8; 29]);
        let key = WatermarkKey::new(&p, &Chain::ICP);
        assert_eq!(key.0[29], 0); // ICP discriminant
    }

    #[test]
    fn test_watermark_key_chain_discriminants() {
        let p = Principal::from_slice(&[2u8; 29]);
        assert_eq!(WatermarkKey::new(&p, &Chain::ICP).0[29], 0);
        assert_eq!(WatermarkKey::new(&p, &Chain::CkBTC).0[29], 1);
        assert_eq!(WatermarkKey::new(&p, &Chain::CkETH).0[29], 2);
    }

    #[test]
    fn test_watermark_key_storable_roundtrip() {
        let p = Principal::from_slice(&[3u8; 29]);
        let key = WatermarkKey::new(&p, &Chain::CkBTC);
        let key2 = WatermarkKey::from_bytes(key.to_bytes());
        assert_eq!(key, key2);
    }

    #[test]
    fn test_watermark_key_ordering() {
        let p1 = Principal::from_slice(&[1u8; 29]);
        let p2 = Principal::from_slice(&[2u8; 29]);
        let k1 = WatermarkKey::new(&p1, &Chain::ICP);
        let k2 = WatermarkKey::new(&p2, &Chain::ICP);
        assert!(k1 < k2);
    }

    // --- Chain ---------------------------------------------------------------

    #[test]
    fn test_chain_discriminant_roundtrip() {
        for chain in [Chain::ICP, Chain::CkBTC, Chain::CkETH] {
            let d = chain.discriminant();
            let back = Chain::from_discriminant(d).unwrap();
            assert_eq!(chain, back);
        }
    }

    #[test]
    fn test_chain_unknown_discriminant() {
        assert!(Chain::from_discriminant(99).is_none());
    }

    // --- AlertRecord ---------------------------------------------------------

    #[test]
    fn test_alert_record_creation() {
        let rec = AlertRecord {
            alert_id: "alert-001".to_string(),
            timestamp: 1_709_000_000_000_000_000,
            user: Principal::from_slice(&[4u8; 29]),
            rules_triggered: vec!["large_transfer".to_string()],
            severity: 7,
            status: AlertStatus::Pending,
        };
        assert_eq!(rec.alert_id, "alert-001");
        assert_eq!(rec.severity, 7);
        assert_eq!(rec.status, AlertStatus::Pending);
    }

    #[test]
    fn test_alert_record_status_transitions() {
        let mut rec = AlertRecord {
            alert_id: "alert-002".to_string(),
            timestamp: 0,
            user: Principal::from_slice(&[5u8; 29]),
            rules_triggered: vec![],
            severity: 3,
            status: AlertStatus::Pending,
        };
        assert_eq!(rec.status, AlertStatus::Pending);
        rec.status = AlertStatus::Sent;
        assert_eq!(rec.status, AlertStatus::Sent);
        rec.status = AlertStatus::Failed;
        assert_eq!(rec.status, AlertStatus::Failed);
    }

    #[test]
    fn test_alert_record_storable_roundtrip() {
        let rec = AlertRecord {
            alert_id: "alert-003".to_string(),
            timestamp: 999,
            user: Principal::from_slice(&[6u8; 29]),
            rules_triggered: vec!["rapid_tx".to_string(), "new_address".to_string()],
            severity: 10,
            status: AlertStatus::Sent,
        };
        let bytes = rec.to_bytes();
        let rec2 = AlertRecord::from_bytes(bytes);
        assert_eq!(rec2.alert_id, "alert-003");
        assert_eq!(rec2.rules_triggered.len(), 2);
        assert_eq!(rec2.status, AlertStatus::Sent);
    }

    // --- UnifiedEvent --------------------------------------------------------

    #[test]
    fn test_unified_event_fields() {
        let ev = UnifiedEvent {
            chain: "ICP".to_string(),
            timestamp: 100,
            direction: Direction::Out,
            amount_e8s: 1_000_000,
            counterparty: Principal::anonymous(),
            tx_id: "some-tx-id".to_string(),
        };
        assert_eq!(ev.chain, "ICP");
        assert_eq!(ev.direction, Direction::Out);
        assert_eq!(ev.amount_e8s, 1_000_000);
    }

    #[test]
    fn test_unified_event_direction_variants() {
        let e_in = UnifiedEvent {
            chain: "CkBTC".to_string(),
            timestamp: 0,
            direction: Direction::In,
            amount_e8s: 500,
            counterparty: Principal::anonymous(),
            tx_id: "in-tx".to_string(),
        };
        let e_out = UnifiedEvent {
            chain: "CkBTC".to_string(),
            timestamp: 0,
            direction: Direction::Out,
            amount_e8s: 500,
            counterparty: Principal::anonymous(),
            tx_id: "out-tx".to_string(),
        };
        assert_eq!(e_in.direction, Direction::In);
        assert_eq!(e_out.direction, Direction::Out);
    }

    // --- EngineHealthStatus --------------------------------------------------

    #[test]
    fn test_engine_health_status_structure() {
        let hs = EngineHealthStatus {
            cycle_balance: 1_000_000_000_000,
            last_tick: 42,
            is_running: true,
            watermark_count: 3,
        };
        assert!(hs.is_running);
        assert_eq!(hs.watermark_count, 3);
        assert!(hs.cycle_balance > 0);
    }

    // --- Timer mock ----------------------------------------------------------

    #[test]
    fn test_timer_initialization_flag() {
        // Simulate what init() does to the IS_RUNNING flag
        IS_RUNNING.with(|r| *r.borrow_mut() = true);
        let running = IS_RUNNING.with(|r| *r.borrow());
        assert!(running);
    }

    // --- LastTick stored/retrieved -------------------------------------------

    #[test]
    fn test_last_tick_roundtrip() {
        let lt = LastTick { value: 123_456_789 };
        let bytes = lt.to_bytes();
        let lt2 = LastTick::from_bytes(bytes);
        assert_eq!(lt2.value, 123_456_789);
    }

    // =========================================================================
    // Phase 1d: Detection Engine Tests
    // =========================================================================
    mod detector_tests {
        use super::*;
        use crate::detector::{
            evaluate, rule_a1_large_transfer, rule_a3_rapid_transactions, rule_a4_new_address,
            DetectionContext, Severity,
        };

        fn make_out_event(amount: u64, counterparty: Principal, ts: u64) -> UnifiedEvent {
            UnifiedEvent {
                chain: "ICP".to_string(),
                timestamp: ts,
                direction: Direction::Out,
                amount_e8s: amount,
                counterparty,
                tx_id: format!("tx-{}", ts),
            }
        }

        fn make_in_event(amount: u64, ts: u64) -> UnifiedEvent {
            UnifiedEvent {
                chain: "ICP".to_string(),
                timestamp: ts,
                direction: Direction::In,
                amount_e8s: amount,
                counterparty: Principal::anonymous(),
                tx_id: format!("in-{}", ts),
            }
        }

        // --- A1: Large transfer ---

        #[test]
        fn test_a1_large_transfer_detected() {
            let events = vec![make_out_event(60, Principal::anonymous(), 1000)];
            let result = rule_a1_large_transfer(&events, 100);
            assert!(result.is_some());
            assert_eq!(result.unwrap().rule_id, "A1");
        }

        #[test]
        fn test_a1_small_transfer_ignored() {
            let events = vec![make_out_event(40, Principal::anonymous(), 1000)];
            let result = rule_a1_large_transfer(&events, 100);
            assert!(result.is_none());
        }

        #[test]
        fn test_a1_exactly_50_percent_not_triggered() {
            // 50/100 = 50%, threshold is > 50% so exactly 50 should NOT trigger
            let events = vec![make_out_event(50, Principal::anonymous(), 1000)];
            let result = rule_a1_large_transfer(&events, 100);
            assert!(result.is_none(), "Exactly 50% should not trigger A1");
        }

        #[test]
        fn test_a1_51_percent_triggered() {
            // 51/100 = 51% — should trigger
            let events = vec![make_out_event(51, Principal::anonymous(), 1000)];
            let result = rule_a1_large_transfer(&events, 100);
            assert!(result.is_some(), "51% should trigger A1");
        }

        #[test]
        fn test_a1_zero_balance_no_trigger() {
            let events = vec![make_out_event(100, Principal::anonymous(), 1000)];
            let result = rule_a1_large_transfer(&events, 0);
            assert!(result.is_none(), "Zero balance should not trigger A1");
        }

        #[test]
        fn test_a1_incoming_tx_not_triggered() {
            let events = vec![make_in_event(999, 1000)];
            let result = rule_a1_large_transfer(&events, 100);
            assert!(result.is_none());
        }

        #[test]
        fn test_a1_weight_is_7() {
            let events = vec![make_out_event(51, Principal::anonymous(), 1000)];
            let m = rule_a1_large_transfer(&events, 100).unwrap();
            assert_eq!(m.weight, 7);
        }

        // --- A3: Rapid transactions ---

        fn make_n_out_events(n: usize, start_ts: u64, interval_ns: u64) -> Vec<UnifiedEvent> {
            (0..n)
                .map(|i| make_out_event(1, Principal::anonymous(), start_ts + i as u64 * interval_ns))
                .collect()
        }

        #[test]
        fn test_a3_five_txs_not_triggered() {
            // Exactly 5 outgoing txs in 10 min — should NOT trigger (threshold is >5)
            let events = make_n_out_events(5, 0, 60_000_000_000); // 1 min apart
            let result = rule_a3_rapid_transactions(&events);
            assert!(result.is_none(), "5 txs should not trigger A3");
        }

        #[test]
        fn test_a3_six_txs_triggered() {
            // 6 txs within 10 min — should trigger
            let events = make_n_out_events(6, 0, 60_000_000_000); // 1 min apart, total 5 min
            let result = rule_a3_rapid_transactions(&events);
            assert!(result.is_some(), "6 txs in 10 min should trigger A3");
        }

        #[test]
        fn test_a3_six_txs_outside_10min_not_triggered() {
            // 6 txs but spaced so no 6 fit within 10 min window
            // 6 txs at 2 min intervals = span 10 min (0, 2, 4, 6, 8, 10 minutes)
            // Window is [0, 10min] inclusive — 11 min span means last falls outside
            let min = 60_000_000_000u64;
            let events = make_n_out_events(6, 0, 2 * min + 1); // slightly over 2 min apart → 10min+5s span
            let result = rule_a3_rapid_transactions(&events);
            assert!(result.is_none(), "6 txs spanning >10 min should not trigger A3");
        }

        #[test]
        fn test_a3_weight_is_3() {
            let events = make_n_out_events(6, 0, 60_000_000_000);
            let m = rule_a3_rapid_transactions(&events).unwrap();
            assert_eq!(m.weight, 3);
        }

        #[test]
        fn test_a3_empty_events_not_triggered() {
            let result = rule_a3_rapid_transactions(&[]);
            assert!(result.is_none());
        }

        #[test]
        fn test_a3_incoming_txs_not_counted() {
            // 10 incoming txs — should not trigger (only outgoing counted)
            let events: Vec<UnifiedEvent> = (0..10)
                .map(|i| make_in_event(1, i * 60_000_000_000))
                .collect();
            let result = rule_a3_rapid_transactions(&events);
            assert!(result.is_none());
        }

        // --- A4: New destination address ---

        #[test]
        fn test_a4_known_address_not_triggered() {
            let p = Principal::from_slice(&[42u8; 29]);
            let events = vec![make_out_event(100, p, 1000)];
            let allowlist = vec![p.to_text()];
            let result = rule_a4_new_address(&events, &allowlist);
            assert!(result.is_none());
        }

        #[test]
        fn test_a4_unknown_address_triggered() {
            let p = Principal::from_slice(&[42u8; 29]);
            let events = vec![make_out_event(100, p, 1000)];
            let allowlist: Vec<String> = vec![];
            let result = rule_a4_new_address(&events, &allowlist);
            assert!(result.is_some(), "Unknown address should trigger A4");
        }

        #[test]
        fn test_a4_weight_is_1() {
            let p = Principal::from_slice(&[1u8; 29]);
            let events = vec![make_out_event(100, p, 1000)];
            let m = rule_a4_new_address(&events, &[]).unwrap();
            assert_eq!(m.weight, 1);
        }

        #[test]
        fn test_a4_incoming_ignored() {
            let events = vec![make_in_event(100, 1000)];
            let result = rule_a4_new_address(&events, &[]);
            assert!(result.is_none());
        }

        #[test]
        fn test_a4_empty_events_not_triggered() {
            let result = rule_a4_new_address(&[], &[]);
            assert!(result.is_none());
        }

        // --- Scoring ---

        fn make_ctx<'a>(
            events: &'a [UnifiedEvent],
            balance: u64,
            allowlist: &'a [String],
            threshold: u8,
        ) -> DetectionContext<'a> {
            DetectionContext {
                events,
                estimated_balance_e8s: balance,
                allowlisted_addresses: allowlist,
                alert_threshold: threshold,
            }
        }

        #[test]
        fn test_score_a1_only_equals_7() {
            // A1 only: large transfer, no rapid txs (only 1 tx), known address
            let p = Principal::from_slice(&[7u8; 29]);
            let events = vec![make_out_event(51, p, 1000)];
            let allowlist = vec![p.to_text()];
            let ctx = make_ctx(&events, 100, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 7);
            assert_eq!(result.rules_triggered.len(), 1);
            assert_eq!(result.rules_triggered[0].rule_id, "A1");
        }

        #[test]
        fn test_score_a3_only_equals_3() {
            // 6 outgoing in 10 min, all going to same known address, small amounts
            let p = Principal::from_slice(&[8u8; 29]);
            let allowlist = vec![p.to_text()];
            let events = make_n_out_events(6, 0, 60_000_000_000)
                .into_iter()
                .map(|mut e| { e.counterparty = p; e })
                .collect::<Vec<_>>();
            // Balance large enough that no single tx > 50%
            let ctx = make_ctx(&events, 1_000_000, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 3);
        }

        #[test]
        fn test_score_a1_plus_a3_equals_10() {
            let p = Principal::from_slice(&[9u8; 29]);
            let allowlist = vec![p.to_text()];
            // 6 txs in 10 min, one is large (>50% of balance)
            let mut events = make_n_out_events(6, 0, 60_000_000_000)
                .into_iter()
                .map(|mut e| { e.counterparty = p; e.amount_e8s = 1; e })
                .collect::<Vec<_>>();
            // Override first to be large
            events[0].amount_e8s = 51;
            let ctx = make_ctx(&events, 100, &allowlist, 7);
            let result = evaluate(&ctx);
            // A1(7) + A3(3) = 10
            assert_eq!(result.score, 10);
        }

        // --- Threshold / should_alert ---

        #[test]
        fn test_threshold_score_equals_threshold_alerts() {
            // score 7, threshold 7 → should_alert = true
            let p = Principal::from_slice(&[10u8; 29]);
            let events = vec![make_out_event(51, p, 1000)];
            let allowlist = vec![p.to_text()];
            let ctx = make_ctx(&events, 100, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 7);
            assert!(result.should_alert);
        }

        #[test]
        fn test_threshold_score_below_threshold_no_alert() {
            // score 3, threshold 7 → should_alert = false
            let p = Principal::from_slice(&[11u8; 29]);
            let allowlist = vec![p.to_text()];
            let events = make_n_out_events(6, 0, 60_000_000_000)
                .into_iter()
                .map(|mut e| { e.counterparty = p; e })
                .collect::<Vec<_>>();
            let ctx = make_ctx(&events, 1_000_000, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 3);
            assert!(!result.should_alert);
        }

        #[test]
        fn test_no_rules_triggered() {
            // No events → no rules triggered, score 0
            let ctx = make_ctx(&[], 1000, &[], 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 0);
            assert!(result.rules_triggered.is_empty());
            assert!(!result.should_alert);
        }

        // --- Severity enum ---

        #[test]
        fn test_severity_from_score_info() {
            assert_eq!(Severity::from_score(0), Severity::Info);
            assert_eq!(Severity::from_score(2), Severity::Info);
        }

        #[test]
        fn test_severity_from_score_warn() {
            assert_eq!(Severity::from_score(3), Severity::Warn);
            assert_eq!(Severity::from_score(6), Severity::Warn);
        }

        #[test]
        fn test_severity_from_score_critical() {
            assert_eq!(Severity::from_score(7), Severity::Critical);
            assert_eq!(Severity::from_score(14), Severity::Critical);
        }

        #[test]
        fn test_severity_from_score_emergency() {
            assert_eq!(Severity::from_score(15), Severity::Emergency);
            assert_eq!(Severity::from_score(255), Severity::Emergency);
        }

        // --- Alert payload ---

        #[test]
        fn test_alert_payload_fields_populated() {
            use crate::alerts::format_alert;
            let p = Principal::from_slice(&[20u8; 29]);
            let dest = Principal::from_slice(&[21u8; 29]);
            // Put dest in allowlist so A4 doesn't fire, only A1 (score=7)
            let allowlist = vec![dest.to_text()];
            let events = vec![make_out_event(51, dest, 1000)];
            let ctx = make_ctx(&events, 100, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 7, "Expected only A1 to fire");
            let payload = format_alert(p, result, events, 1_700_000_000_000_000_000u64);
            assert!(!payload.alert_id.is_empty());
            assert_eq!(payload.user, p);
            assert_eq!(payload.severity, "CRITICAL");
            assert_eq!(payload.severity_score, 7);
            assert!(!payload.rules_triggered.is_empty());
            assert!(!payload.events_summary.is_empty());
            assert!(!payload.recommended_action.is_empty());
        }

        #[test]
        fn test_alert_payload_no_events_summary() {
            use crate::alerts::format_alert;
            let p = Principal::from_slice(&[21u8; 29]);
            // Manually build a result with should_alert true but no events
            let result = crate::detector::DetectionResult {
                score: 7,
                severity: Severity::Critical,
                rules_triggered: vec![crate::detector::RuleMatch {
                    rule_id: "A1".to_string(),
                    description: "test".to_string(),
                    weight: 7,
                }],
                should_alert: true,
            };
            let payload = format_alert(p, result, vec![], 1000);
            assert_eq!(payload.events_summary, "No events");
        }

        // --- Edge cases ---

        #[test]
        fn test_a1_empty_events() {
            let result = rule_a1_large_transfer(&[], 1000);
            assert!(result.is_none());
        }

        #[test]
        fn test_a3_four_txs_not_triggered() {
            let events = make_n_out_events(4, 0, 60_000_000_000);
            assert!(rule_a3_rapid_transactions(&events).is_none());
        }

        #[test]
        fn test_evaluate_all_three_rules() {
            // A1 + A3 + A4 all triggered → score 11
            let unknown = Principal::from_slice(&[99u8; 29]);
            let mut events = make_n_out_events(6, 0, 60_000_000_000)
                .into_iter()
                .map(|mut e| { e.counterparty = unknown; e.amount_e8s = 1; e })
                .collect::<Vec<_>>();
            events[0].amount_e8s = 51; // trigger A1
            let allowlist: Vec<String> = vec![];
            let ctx = make_ctx(&events, 100, &allowlist, 7);
            let result = evaluate(&ctx);
            assert_eq!(result.score, 11); // A1(7)+A3(3)+A4(1)
            assert!(result.should_alert);
            assert_eq!(result.severity, Severity::Critical);
        }
    }
}
